import type { ToolCategory, ToolCategoryId } from "@/types/tools";

/**
 * CV-driven learning catalog. Concepts and links point at each tool's
 * official documentation — not any application source tree.
 */
export const toolCategories: readonly ToolCategory[] = [
  {
    id: "test-automation",
    title: "Test Automation Tools",
    summary: "Browser, mobile, and enterprise automation platforms from the QA toolkit.",
    tools: [
      {
        id: "playwright",
        name: "Playwright",
        summary: "Modern end-to-end testing for Chromium, Firefox, and WebKit.",
        docsUrl: "https://playwright.dev/docs/intro",
        docsLabel: "playwright.dev",
        calls: [
          {
            id: "goto",
            signature: "page.goto(url)",
            summary: "Navigate and wait for a lifecycle event.",
            why: "First building block of every UI journey.",
            docsUrl: "https://playwright.dev/docs/navigations",
          },
          {
            id: "get-by-role",
            signature: "page.getByRole(role, options)",
            summary: "Locate by accessibility role and name.",
            why: "Official guidance prefers user-facing locators over CSS.",
            docsUrl: "https://playwright.dev/docs/locators",
          },
          {
            id: "expect",
            signature: "expect(locator).toBeVisible()",
            summary: "Web-first assertion with auto-wait.",
            why: "Removes sleeps; assertions retry until timeout.",
            docsUrl: "https://playwright.dev/docs/test-assertions",
          },
        ],
      },
      {
        id: "selenium",
        name: "Selenium",
        summary: "W3C WebDriver automation for browsers across languages.",
        docsUrl: "https://www.selenium.dev/documentation/",
        docsLabel: "selenium.dev",
        calls: [
          {
            id: "get",
            signature: "driver.get(url)",
            summary: "Load a page in the controlled browser.",
            why: "Core WebDriver navigation entry point.",
            docsUrl: "https://www.selenium.dev/documentation/webdriver/interactions/navigation/",
          },
          {
            id: "find-element",
            signature: "driver.findElement(By...)",
            summary: "Locate a single element with a strategy.",
            why: "Foundation of page-object patterns in Selenium.",
            docsUrl: "https://www.selenium.dev/documentation/webdriver/elements/locators/",
          },
          {
            id: "waits",
            signature: "WebDriverWait / explicit waits",
            summary: "Wait for conditions before interacting.",
            why: "Official docs stress waits over Thread.sleep.",
            docsUrl: "https://www.selenium.dev/documentation/webdriver/waits/",
          },
        ],
      },
      {
        id: "cypress",
        name: "Cypress",
        summary: "Developer-friendly E2E testing for modern web apps.",
        docsUrl: "https://docs.cypress.io/",
        docsLabel: "docs.cypress.io",
        calls: [
          {
            id: "visit",
            signature: "cy.visit(url)",
            summary: "Open an application URL in the Cypress runner.",
            why: "Starts every Cypress spec.",
            docsUrl: "https://docs.cypress.io/api/commands/visit",
          },
          {
            id: "get",
            signature: "cy.get(selector)",
            summary: "Query the DOM with retry-ability.",
            why: "Cypress commands automatically retry until they pass.",
            docsUrl: "https://docs.cypress.io/api/commands/get",
          },
          {
            id: "intercept",
            signature: "cy.intercept(method, url)",
            summary: "Stub or spy on network requests.",
            why: "Critical for stable UI tests of API-backed pages.",
            docsUrl: "https://docs.cypress.io/api/commands/intercept",
          },
        ],
      },
      {
        id: "accelq",
        name: "AccelQ",
        summary: "Codeless/AI-assisted enterprise test automation platform.",
        docsUrl: "https://support.accelq.com/",
        docsLabel: "support.accelq.com",
        calls: [
          {
            id: "actions",
            signature: "Action logic / scenarios",
            summary: "Compose reusable business actions in AccelQ.",
            why: "Enterprise suites scale via reusable action libraries.",
            docsUrl: "https://support.accelq.com/",
          },
          {
            id: "data-driven",
            signature: "Data-driven test design",
            summary: "Parameterize scenarios with external data.",
            why: "Coverage expands without duplicating flows.",
            docsUrl: "https://support.accelq.com/",
          },
          {
            id: "ci-hooks",
            signature: "CI/CD execution hooks",
            summary: "Run AccelQ suites from pipeline agents.",
            why: "Regression must gate releases like any other automation.",
            docsUrl: "https://support.accelq.com/",
          },
        ],
      },
      {
        id: "cucumber",
        name: "Cucumber",
        summary: "BDD — executable specifications in Gherkin.",
        docsUrl: "https://cucumber.io/docs/cucumber/",
        docsLabel: "cucumber.io",
        calls: [
          {
            id: "feature",
            signature: "Feature / Scenario (Gherkin)",
            summary: "Describe behavior in business-readable steps.",
            why: "Aligns QA, dev, and stakeholders on acceptance criteria.",
            docsUrl: "https://cucumber.io/docs/gherkin/reference/",
          },
          {
            id: "step-defs",
            signature: "Step definitions",
            summary: "Bind Gherkin steps to automation code.",
            why: "Keeps readable specs wired to real checks.",
            docsUrl: "https://cucumber.io/docs/cucumber/step-definitions/",
          },
          {
            id: "hooks",
            signature: "Before / After hooks",
            summary: "Setup and teardown around scenarios.",
            why: "Isolate state without cluttering feature files.",
            docsUrl: "https://cucumber.io/docs/cucumber/api/#hooks",
          },
        ],
      },
      {
        id: "appium",
        name: "Appium",
        summary: "Cross-platform mobile UI automation.",
        docsUrl: "https://appium.io/docs/en/latest/",
        docsLabel: "appium.io",
        calls: [
          {
            id: "create-session",
            signature: "driver = create session (capabilities)",
            summary: "Start an Appium session with device caps.",
            why: "Capabilities define platform, app, and automation engine.",
            docsUrl: "https://appium.io/docs/en/latest/guides/caps/",
          },
          {
            id: "find-element",
            signature: "driver.findElement / $()",
            summary: "Locate mobile elements by strategy.",
            why: "Same WebDriver mindset as desktop, different locators.",
            docsUrl: "https://appium.io/docs/en/latest/guides/migrating-1-to-2/",
          },
          {
            id: "gestures",
            signature: "mobile gestures / actions",
            summary: "Tap, swipe, and multi-touch sequences.",
            why: "Mobile UX needs gestures beyond click/type.",
            docsUrl: "https://appium.io/docs/en/latest/guides/actions/",
          },
        ],
      },
      {
        id: "squish",
        name: "Squish",
        summary: "GUI test automation for Qt, desktop, embedded, and mobile.",
        docsUrl: "https://doc.qt.io/squish/",
        docsLabel: "doc.qt.io/squish",
        calls: [
          {
            id: "object-names",
            signature: "Object names / real names",
            summary: "Identify widgets robustly across platforms.",
            why: "Squish suites live or die on stable object naming.",
            docsUrl: "https://doc.qt.io/squish/",
          },
          {
            id: "bdd",
            signature: "BDD / feature integration",
            summary: "Drive Squish tests from Gherkin-style features.",
            why: "Acceptance language stays readable for multi-platform apps.",
            docsUrl: "https://doc.qt.io/squish/",
          },
          {
            id: "vp",
            signature: "Verification points",
            summary: "Capture and compare UI properties or screenshots.",
            why: "Desktop GUIs need property-level as well as visual checks.",
            docsUrl: "https://doc.qt.io/squish/",
          },
        ],
      },
    ],
  },
  {
    id: "frameworks",
    title: "Automation Frameworks",
    summary: "Runners and patterns that structure suites across languages.",
    tools: [
      {
        id: "pytest",
        name: "PyTest",
        summary: "Python testing framework with fixtures and plugins.",
        docsUrl: "https://docs.pytest.org/",
        docsLabel: "docs.pytest.org",
        calls: [
          {
            id: "fixtures",
            signature: "@pytest.fixture",
            summary: "Inject setup/teardown dependencies into tests.",
            why: "Fixtures keep tests focused on behavior.",
            docsUrl: "https://docs.pytest.org/en/stable/fixture.html",
          },
          {
            id: "parametrize",
            signature: "@pytest.mark.parametrize",
            summary: "Run one test with many input rows.",
            why: "Data-driven coverage without copy-paste.",
            docsUrl: "https://docs.pytest.org/en/stable/how-to/parametrize.html",
          },
          {
            id: "markers",
            signature: "@pytest.mark.* / -m",
            summary: "Select subsets of the suite by marker.",
            why: "CI runs smoke vs full regression via markers.",
            docsUrl: "https://docs.pytest.org/en/stable/how-to/mark.html",
          },
        ],
      },
      {
        id: "testng",
        name: "TestNG",
        summary: "Java test runner with suites, groups, and parallel runs.",
        docsUrl: "https://testng.org/doc/",
        docsLabel: "testng.org",
        calls: [
          {
            id: "annotations",
            signature: "@Test / @BeforeMethod",
            summary: "Declare tests and lifecycle hooks.",
            why: "Standard Java automation backbone with Selenium.",
            docsUrl: "https://testng.org/doc/documentation-main.html#annotations",
          },
          {
            id: "groups",
            signature: "groups = { \"smoke\" }",
            summary: "Tag tests for selective execution.",
            why: "Maps cleanly to pipeline stages.",
            docsUrl: "https://testng.org/doc/documentation-main.html#test-groups",
          },
          {
            id: "parallel",
            signature: "parallel suite config",
            summary: "Run methods/classes in parallel.",
            why: "Cuts wall-clock time for large Java suites.",
            docsUrl: "https://testng.org/doc/documentation-main.html#parallel-running",
          },
        ],
      },
      {
        id: "nunit",
        name: "NUnit",
        summary: ".NET unit/integration test framework.",
        docsUrl: "https://docs.nunit.org/",
        docsLabel: "docs.nunit.org",
        calls: [
          {
            id: "test",
            signature: "[Test]",
            summary: "Mark a method as a test case.",
            why: "Primary attribute for C# Selenium/NUnit frameworks.",
            docsUrl: "https://docs.nunit.org/articles/nunit/writing-tests/attributes/test.html",
          },
          {
            id: "test-case",
            signature: "[TestCase(...)]",
            summary: "Parameterized cases inline.",
            why: "Compact data-driven tests in C#.",
            docsUrl: "https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html",
          },
          {
            id: "setup",
            signature: "[SetUp] / [TearDown]",
            summary: "Per-test lifecycle hooks.",
            why: "Browser/driver lifecycle lives here in UI suites.",
            docsUrl: "https://docs.nunit.org/articles/nunit/writing-tests/attributes/setup.html",
          },
        ],
      },
      {
        id: "mocha",
        name: "Mocha",
        summary: "Flexible JavaScript test runner.",
        docsUrl: "https://mochajs.org/",
        docsLabel: "mochajs.org",
        calls: [
          {
            id: "describe-it",
            signature: "describe / it",
            summary: "Organize and declare JS tests.",
            why: "De-facto structure for Node and browser test code.",
            docsUrl: "https://mochajs.org/#getting-started",
          },
          {
            id: "hooks",
            signature: "before / after / beforeEach",
            summary: "Lifecycle hooks around suites.",
            why: "Shared setup for UI or API specs.",
            docsUrl: "https://mochajs.org/#hooks",
          },
          {
            id: "async",
            signature: "async tests / done",
            summary: "Handle promises and callbacks cleanly.",
            why: "Most automation I/O is asynchronous.",
            docsUrl: "https://mochajs.org/#asynchronous-code",
          },
        ],
      },
      {
        id: "robot",
        name: "Robot Framework",
        summary: "Keyword-driven acceptance test automation.",
        docsUrl: "https://robotframework.org/",
        docsLabel: "robotframework.org",
        calls: [
          {
            id: "keywords",
            signature: "User / library keywords",
            summary: "Compose readable keyword steps.",
            why: "Non-dev stakeholders can follow keyword suites.",
            docsUrl: "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-user-keywords",
          },
          {
            id: "variables",
            signature: "${SCALAR} / @{LIST}",
            summary: "Parameterize keywords and resources.",
            why: "Keeps environments and data out of hardcoding.",
            docsUrl: "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variables",
          },
          {
            id: "libraries",
            signature: "Library SeleniumLibrary / Browser",
            summary: "Import automation libraries.",
            why: "UI and API power comes from libraries, not the core alone.",
            docsUrl: "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-test-libraries",
          },
        ],
      },
      {
        id: "webdriverio",
        name: "WebdriverIO",
        summary: "Next-gen browser and mobile automation for Node.",
        docsUrl: "https://webdriver.io/docs/gettingstarted",
        docsLabel: "webdriver.io",
        calls: [
          {
            id: "browser-url",
            signature: "browser.url()",
            summary: "Open a page in the WDIO session.",
            why: "Session API entry for e2e flows.",
            docsUrl: "https://webdriver.io/docs/api/browser/url",
          },
          {
            id: "dollar",
            signature: "$ / $$ selectors",
            summary: "Query elements with retry logic.",
            why: "Concise selector API used across WDIO suites.",
            docsUrl: "https://webdriver.io/docs/api/browser/$",
          },
          {
            id: "wait-until",
            signature: "browser.waitUntil()",
            summary: "Custom expected conditions.",
            why: "Stabilize async UI without fixed sleeps.",
            docsUrl: "https://webdriver.io/docs/api/browser/waitUntil",
          },
        ],
      },
      {
        id: "nightwatch",
        name: "Nightwatch.js",
        summary: "Integrated Node.js E2E testing framework.",
        docsUrl: "https://nightwatchjs.org/guide/",
        docsLabel: "nightwatchjs.org",
        calls: [
          {
            id: "navigate",
            signature: "browser.navigateTo(url)",
            summary: "Open the application under test.",
            why: "Starts Nightwatch journeys.",
            docsUrl: "https://nightwatchjs.org/api/navigateTo.html",
          },
          {
            id: "assert",
            signature: "browser.assert.*",
            summary: "Built-in assertions on page state.",
            why: "Keeps expectations readable in chainable APIs.",
            docsUrl: "https://nightwatchjs.org/api/assert/",
          },
          {
            id: "page-objects",
            signature: "page object model support",
            summary: "Encapsulate selectors and commands.",
            why: "Official guide recommends POM for scale.",
            docsUrl: "https://nightwatchjs.org/guide/using-page-objects/getting-started.html",
          },
        ],
      },
      {
        id: "isafe",
        name: "iSAFE (data-driven)",
        summary: "Enterprise data-driven automation pattern used with Selenium/Java.",
        docsUrl: "https://www.selenium.dev/documentation/test_practices/encouraged/page_object_models/",
        docsLabel: "Data-driven + POM practices",
        calls: [
          {
            id: "data-tables",
            signature: "External test data (CSV/Excel/JSON)",
            summary: "Drive the same flow with many input rows.",
            why: "Data-driven frameworks multiply coverage without cloning scripts.",
            docsUrl: "https://www.selenium.dev/documentation/test_practices/encouraged/",
          },
          {
            id: "pom",
            signature: "Page Object Model",
            summary: "Keep locators/actions out of data rows.",
            why: "Official Selenium guidance pairs POM with maintainable suites.",
            docsUrl: "https://www.selenium.dev/documentation/test_practices/encouraged/page_object_models/",
          },
          {
            id: "keywords",
            signature: "Reusable business keywords",
            summary: "Compose journeys from named actions + data.",
            why: "Keyword + data layers keep enterprise suites readable.",
            docsUrl: "https://cucumber.io/docs/cucumber/step-definitions/",
          },
        ],
      },
      {
        id: "bdd",
        name: "BDD practices",
        summary: "Behavior-driven collaboration patterns (with Cucumber/Gherkin).",
        docsUrl: "https://cucumber.io/docs/bdd/",
        docsLabel: "cucumber.io/bdd",
        calls: [
          {
            id: "three-amigos",
            signature: "Discovery / Three Amigos",
            summary: "Refine examples before automation.",
            why: "BDD fails when examples are written after coding only.",
            docsUrl: "https://cucumber.io/docs/bdd/",
          },
          {
            id: "living-docs",
            signature: "Living documentation",
            summary: "Keep specs executable and current.",
            why: "Regression suite doubles as product docs.",
            docsUrl: "https://cucumber.io/docs/bdd/",
          },
          {
            id: "ubiquitous",
            signature: "Ubiquitous language",
            summary: "Shared terms in features and code.",
            why: "Reduces translation bugs between BA and automation.",
            docsUrl: "https://cucumber.io/docs/bdd/",
          },
        ],
      },
    ],
  },
  {
    id: "api-performance",
    title: "API & Performance",
    summary: "Contract checks and load tools for reliability under stress.",
    tools: [
      {
        id: "api-testing",
        name: "API testing",
        summary: "HTTP contract, status, schema, and negative-path validation.",
        docsUrl: "https://www.postman.com/api-platform/api-testing/",
        docsLabel: "API testing overview",
        calls: [
          {
            id: "status",
            signature: "Assert status codes",
            summary: "Verify 2xx/4xx/5xx contracts per operation.",
            why: "Status is the first gate of any API suite.",
            docsUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
          },
          {
            id: "schema",
            signature: "JSON Schema / OpenAPI validation",
            summary: "Fail on unexpected fields or types.",
            why: "Breaking changes hide behind HTTP 200.",
            docsUrl: "https://json-schema.org/learn/getting-started-step-by-step",
          },
          {
            id: "auth",
            signature: "Auth flows (token / OAuth)",
            summary: "Positive and negative authorization paths.",
            why: "Security defects often show up as API auth gaps.",
            docsUrl: "https://oauth.net/2/",
          },
        ],
      },
      {
        id: "jmeter",
        name: "Apache JMeter",
        summary: "Load and performance testing of web apps and APIs.",
        docsUrl: "https://jmeter.apache.org/usermanual/index.html",
        docsLabel: "jmeter.apache.org",
        calls: [
          {
            id: "thread-group",
            signature: "Thread Group",
            summary: "Define virtual users and ramp-up.",
            why: "Load shape starts with thread configuration.",
            docsUrl: "https://jmeter.apache.org/usermanual/component_reference.html#ThreadGroup",
          },
          {
            id: "http-sampler",
            signature: "HTTP Request sampler",
            summary: "Hit endpoints under load.",
            why: "Primary sampler for API performance.",
            docsUrl: "https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Request",
          },
          {
            id: "listeners",
            signature: "Listeners / reports",
            summary: "Aggregate latency and error rates.",
            why: "You cannot improve what you do not measure.",
            docsUrl: "https://jmeter.apache.org/usermanual/component_reference.html#listeners",
          },
        ],
      },
      {
        id: "k6",
        name: "Grafana k6",
        summary: "Modern load testing with JS scripts and thresholds.",
        docsUrl: "https://grafana.com/docs/k6/latest/",
        docsLabel: "grafana.com/docs/k6",
        calls: [
          {
            id: "http-get",
            signature: "http.get(url)",
            summary: "Issue an HTTP request in a VU script.",
            why: "Core API for API performance scenarios.",
            docsUrl: "https://grafana.com/docs/k6/latest/javascript-api/k6-http/get/",
          },
          {
            id: "thresholds",
            signature: "options.thresholds",
            summary: "Fail the test when SLOs break.",
            why: "Performance gates belong in CI criteria.",
            docsUrl: "https://grafana.com/docs/k6/latest/using-k6/thresholds/",
          },
          {
            id: "checks",
            signature: "check(res, {...})",
            summary: "Functional assertions during load.",
            why: "Load without checks is just traffic.",
            docsUrl: "https://grafana.com/docs/k6/latest/using-k6/checks/",
          },
        ],
      },
      {
        id: "artillery",
        name: "Artillery",
        summary: "Cloud-scale load & synthetic testing toolkit.",
        docsUrl: "https://www.artillery.io/docs",
        docsLabel: "artillery.io/docs",
        calls: [
          {
            id: "scenarios",
            signature: "scenarios / flows (YAML)",
            summary: "Declare virtual-user journeys.",
            why: "Readable load scripts for mixed HTTP flows.",
            docsUrl: "https://www.artillery.io/docs/get-started/first-test",
          },
          {
            id: "engines",
            signature: "engines (http, playwright, …)",
            summary: "Choose protocol/UI engines per test.",
            why: "API and browser load can share one runner.",
            docsUrl: "https://www.artillery.io/docs",
          },
          {
            id: "processors",
            signature: "processor functions",
            summary: "Custom JS hooks for dynamic data.",
            why: "Realistic load needs parameterized payloads.",
            docsUrl: "https://www.artillery.io/docs",
          },
        ],
      },
    ],
  },
  {
    id: "databases",
    title: "Databases & Data",
    summary: "SQL platforms used for integrity and test-data validation.",
    tools: [
      {
        id: "sql",
        name: "SQL",
        summary: "Structured query language for relational data checks.",
        docsUrl: "https://www.w3schools.com/sql/",
        docsLabel: "SQL reference",
        calls: [
          {
            id: "select-join",
            signature: "SELECT … JOIN",
            summary: "Reconcile entities across tables.",
            why: "UI/API-to-DB checks usually need joins.",
            docsUrl: "https://www.postgresql.org/docs/current/tutorial-join.html",
          },
          {
            id: "aggregates",
            signature: "COUNT / SUM / GROUP BY",
            summary: "Assert totals and integrity aggregates.",
            why: "Money and inventory bugs show up in aggregates.",
            docsUrl: "https://www.postgresql.org/docs/current/tutorial-agg.html",
          },
          {
            id: "constraints",
            signature: "PK / FK / UNIQUE checks",
            summary: "Validate relational constraints hold.",
            why: "Orphan rows are classic data-quality defects.",
            docsUrl: "https://www.postgresql.org/docs/current/ddl-constraints.html",
          },
        ],
      },
      {
        id: "postgresql",
        name: "PostgreSQL",
        summary: "Advanced open-source relational database.",
        docsUrl: "https://www.postgresql.org/docs/current/",
        docsLabel: "postgresql.org/docs",
        calls: [
          {
            id: "psql",
            signature: "psql meta-commands",
            summary: "Inspect schemas and run ad-hoc SQL.",
            why: "Fast triage during data-integrity investigations.",
            docsUrl: "https://www.postgresql.org/docs/current/app-psql.html",
          },
          {
            id: "transactions",
            signature: "BEGIN / COMMIT / ROLLBACK",
            summary: "Control transactional test data.",
            why: "Isolated tests need clean rollback strategies.",
            docsUrl: "https://www.postgresql.org/docs/current/tutorial-transactions.html",
          },
          {
            id: "explain",
            signature: "EXPLAIN ANALYZE",
            summary: "Understand slow validation queries.",
            why: "Heavy reconciliation SQL must stay CI-friendly.",
            docsUrl: "https://www.postgresql.org/docs/current/sql-explain.html",
          },
        ],
      },
      {
        id: "snowflake",
        name: "Snowflake",
        summary: "Cloud data platform for analytics-scale validation.",
        docsUrl: "https://docs.snowflake.com/",
        docsLabel: "docs.snowflake.com",
        calls: [
          {
            id: "warehouses",
            signature: "Virtual warehouses",
            summary: "Size compute for query workloads.",
            why: "Perf of data checks depends on warehouse sizing.",
            docsUrl: "https://docs.snowflake.com/en/user-guide/warehouses",
          },
          {
            id: "time-travel",
            signature: "Time Travel / clones",
            summary: "Query historical data for audit-style checks.",
            why: "Useful when validating migrations and backfills.",
            docsUrl: "https://docs.snowflake.com/en/user-guide/data-time-travel",
          },
          {
            id: "snowsql",
            signature: "SnowSQL / SQL API",
            summary: "Run SQL against Snowflake from automation.",
            why: "Pipelines need a stable client for integrity jobs.",
            docsUrl: "https://docs.snowflake.com/en/user-guide/snowsql",
          },
        ],
      },
    ],
  },
  {
    id: "cloud-cicd",
    title: "Cloud & CI/CD",
    summary: "Cloud hosts and pipelines that run continuous testing.",
    tools: [
      {
        id: "azure-devops",
        name: "Azure DevOps",
        summary: "Boards, repos, and Pipelines for enterprise delivery.",
        docsUrl: "https://learn.microsoft.com/en-us/azure/devops/",
        docsLabel: "learn.microsoft.com/azure/devops",
        calls: [
          {
            id: "yaml-pipeline",
            signature: "azure-pipelines.yml",
            summary: "Declare CI stages, jobs, and steps.",
            why: "Daily regression lives in pipeline YAML.",
            docsUrl: "https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema",
          },
          {
            id: "pr-validation",
            signature: "PR build validation",
            summary: "Require checks before merge.",
            why: "Shift-left quality gate for every change.",
            docsUrl: "https://learn.microsoft.com/en-us/azure/devops/pipelines/policies/build-validation",
          },
          {
            id: "environments",
            signature: "Environments / approvals",
            summary: "Gate deployments with reviewers.",
            why: "Release readiness needs human + automated signals.",
            docsUrl: "https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments",
          },
        ],
      },
      {
        id: "jenkins",
        name: "Jenkins",
        summary: "Extensible open-source automation server.",
        docsUrl: "https://www.jenkins.io/doc/",
        docsLabel: "jenkins.io/doc",
        calls: [
          {
            id: "pipeline",
            signature: "Jenkinsfile (Declarative)",
            summary: "Codify build/test/deploy stages.",
            why: "Regression grids are pipeline-as-code.",
            docsUrl: "https://www.jenkins.io/doc/book/pipeline/",
          },
          {
            id: "agents",
            signature: "Agents / nodes",
            summary: "Distribute jobs across executors/VMs.",
            why: "Large UI matrices need many agents.",
            docsUrl: "https://www.jenkins.io/doc/book/using/using-agents/",
          },
          {
            id: "plugins",
            signature: "Plugin ecosystem",
            summary: "JUnit, HTML publisher, credentials, etc.",
            why: "Reporting and secrets come from plugins.",
            docsUrl: "https://www.jenkins.io/doc/book/managing/plugins/",
          },
        ],
      },
      {
        id: "docker",
        name: "Docker",
        summary: "Container runtime for reproducible test environments.",
        docsUrl: "https://docs.docker.com/",
        docsLabel: "docs.docker.com",
        calls: [
          {
            id: "dockerfile",
            signature: "Dockerfile",
            summary: "Define an image with browsers/tools.",
            why: "Same image locally and in CI reduces “works on my machine”.",
            docsUrl: "https://docs.docker.com/reference/dockerfile/",
          },
          {
            id: "compose",
            signature: "docker compose",
            summary: "Multi-service stacks for app + deps.",
            why: "API/DB tests need orchestrated dependencies.",
            docsUrl: "https://docs.docker.com/compose/",
          },
          {
            id: "run",
            signature: "docker run",
            summary: "Execute one-off containers in pipelines.",
            why: "Jobs often wrap test commands in containers.",
            docsUrl: "https://docs.docker.com/reference/cli/docker/container/run/",
          },
        ],
      },
      {
        id: "aws",
        name: "AWS",
        summary: "Cloud services hosting apps and test infrastructure.",
        docsUrl: "https://docs.aws.amazon.com/",
        docsLabel: "docs.aws.amazon.com",
        calls: [
          {
            id: "iam",
            signature: "IAM roles & policies",
            summary: "Least-privilege access for automation.",
            why: "Test jobs must not use long-lived root keys.",
            docsUrl: "https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html",
          },
          {
            id: "s3",
            signature: "S3 artifacts",
            summary: "Store reports, traces, and baselines.",
            why: "CI needs durable artifact storage.",
            docsUrl: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html",
          },
          {
            id: "ecs-ec2",
            signature: "Compute for runners",
            summary: "Host agents or app under test.",
            why: "Automation enablement often targets AWS-hosted envs.",
            docsUrl: "https://docs.aws.amazon.com/ecs/",
          },
        ],
      },
      {
        id: "azure",
        name: "Microsoft Azure",
        summary: "Cloud platform for apps, data, and DevOps integration.",
        docsUrl: "https://learn.microsoft.com/en-us/azure/",
        docsLabel: "learn.microsoft.com/azure",
        calls: [
          {
            id: "app-service",
            signature: "App Service / deployments",
            summary: "Understand how web apps are hosted.",
            why: "QA validates functional parity after cloud moves.",
            docsUrl: "https://learn.microsoft.com/en-us/azure/app-service/",
          },
          {
            id: "key-vault",
            signature: "Key Vault secrets",
            summary: "Store credentials for test accounts safely.",
            why: "Secrets must not live in repos or plain pipeline vars.",
            docsUrl: "https://learn.microsoft.com/en-us/azure/key-vault/",
          },
          {
            id: "monitor",
            signature: "Azure Monitor",
            summary: "Observe apps during performance tests.",
            why: "Load tests need platform metrics, not only client timings.",
            docsUrl: "https://learn.microsoft.com/en-us/azure/azure-monitor/",
          },
        ],
      },
      {
        id: "git",
        name: "Git",
        summary: "Distributed version control for code and tests.",
        docsUrl: "https://git-scm.com/doc",
        docsLabel: "git-scm.com/doc",
        calls: [
          {
            id: "branch",
            signature: "git branch / checkout / switch",
            summary: "Isolate work on feature branches.",
            why: "PR validation assumes clean branch hygiene.",
            docsUrl: "https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging",
          },
          {
            id: "pr-flow",
            signature: "Pull request workflow",
            summary: "Review automation and product changes together.",
            why: "Code review is part of the QA quality system.",
            docsUrl: "https://docs.github.com/en/pull-requests",
          },
          {
            id: "bisect",
            signature: "git bisect",
            summary: "Find the commit that broke a test.",
            why: "Speeds root-cause on flaky or sudden failures.",
            docsUrl: "https://git-scm.com/docs/git-bisect",
          },
        ],
      },
      {
        id: "bitbucket",
        name: "Bitbucket",
        summary: "Git hosting and Pipelines in the Atlassian ecosystem.",
        docsUrl: "https://support.atlassian.com/bitbucket-cloud/",
        docsLabel: "support.atlassian.com/bitbucket",
        calls: [
          {
            id: "pipelines",
            signature: "bitbucket-pipelines.yml",
            summary: "Define CI steps in Bitbucket Cloud.",
            why: "Alternate enterprise CI host beside Azure/Jenkins.",
            docsUrl: "https://support.atlassian.com/bitbucket-cloud/docs/get-started-with-bitbucket-pipelines/",
          },
          {
            id: "branch-perms",
            signature: "Branch permissions",
            summary: "Protect main with required reviews/builds.",
            why: "Quality gates need enforced branch rules.",
            docsUrl: "https://support.atlassian.com/bitbucket-cloud/docs/use-branch-permissions/",
          },
          {
            id: "prs",
            signature: "Pull requests",
            summary: "Review and merge with checks.",
            why: "Same PR discipline as GitHub/Azure Repos.",
            docsUrl: "https://support.atlassian.com/bitbucket-cloud/docs/pull-requests/",
          },
        ],
      },
    ],
  },
  {
    id: "salesforce",
    title: "Salesforce",
    summary: "CRM clouds and automation validated in enterprise releases.",
    tools: [
      {
        id: "service-cloud",
        name: "Service Cloud",
        summary: "Case management and customer service cloud.",
        docsUrl: "https://developer.salesforce.com/docs",
        docsLabel: "developer.salesforce.com",
        calls: [
          {
            id: "cases",
            signature: "Case object & lifecycle",
            summary: "Understand case create/update/close paths.",
            why: "Service regressions usually hit case workflows first.",
            docsUrl: "https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_case.htm",
          },
          {
            id: "omni",
            signature: "Omni-Channel / routing",
            summary: "Validate work routing to agents.",
            why: "Routing bugs are high-severity for support orgs.",
            docsUrl: "https://help.salesforce.com/s/articleView?id=sf.service_presence_intro.htm",
          },
          {
            id: "api",
            signature: "REST / SOAP APIs",
            summary: "Automate data setup and assertions via API.",
            why: "UI-only Salesforce tests are slow and brittle.",
            docsUrl: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/",
          },
        ],
      },
      {
        id: "experience-cloud",
        name: "Experience Cloud",
        summary: "Branded portals and digital experiences.",
        docsUrl: "https://help.salesforce.com/s/articleView?id=sf.networks_overview.htm",
        docsLabel: "help.salesforce.com",
        calls: [
          {
            id: "sites",
            signature: "Experience Builder sites",
            summary: "Know site types and audiences.",
            why: "Portal UX differs from internal Lightning.",
            docsUrl: "https://help.salesforce.com/s/articleView?id=sf.networks_overview.htm",
          },
          {
            id: "auth",
            signature: "External identity / login",
            summary: "Validate community authentication paths.",
            why: "Auth defects block entire portal releases.",
            docsUrl: "https://help.salesforce.com/s/articleView?id=sf.networks_authentication.htm",
          },
          {
            id: "components",
            signature: "LWC / Aura on experiences",
            summary: "Target components uniquely in UI tests.",
            why: "Shadow DOM / dynamic comps need careful selectors.",
            docsUrl: "https://developer.salesforce.com/docs/platform/lwc/guide",
          },
        ],
      },
      {
        id: "flows",
        name: "Salesforce Flows",
        summary: "Declarative automation for business processes.",
        docsUrl: "https://help.salesforce.com/s/articleView?id=sf.flow.htm",
        docsLabel: "help.salesforce.com/flow",
        calls: [
          {
            id: "record-triggered",
            signature: "Record-triggered flows",
            summary: "Validate automation on create/update.",
            why: "Most regression risk sits in triggered automation.",
            docsUrl: "https://help.salesforce.com/s/articleView?id=sf.flow_concepts_trigger.htm",
          },
          {
            id: "screen-flows",
            signature: "Screen flows",
            summary: "UI-guided processes for users.",
            why: "Need both UI and data assertions per screen.",
            docsUrl: "https://help.salesforce.com/s/articleView?id=sf.flow_concepts_screen.htm",
          },
          {
            id: "debug",
            signature: "Flow debug / interviews",
            summary: "Step through flow interviews while testing.",
            why: "Debug runs explain unexpected field updates.",
            docsUrl: "https://help.salesforce.com/s/articleView?id=sf.flow_test.htm",
          },
        ],
      },
    ],
  },
  {
    id: "ai-evals",
    title: "AI & LLM Evaluation",
    summary: "RAG, judges, agent trajectories, and AI-assisted testing tools.",
    tools: [
      {
        id: "deepeval",
        name: "DeepEval",
        summary: "Open-source LLM evaluation framework (Pytest-style).",
        docsUrl: "https://deepeval.com/docs/getting-started",
        docsLabel: "deepeval.com/docs",
        calls: [
          {
            id: "llm-test-case",
            signature: "LLMTestCase(...)",
            summary: "Pack input, output, context for metrics.",
            why: "Every metric reads from a shared test-case shape.",
            docsUrl: "https://deepeval.com/docs/evaluation-test-cases",
          },
          {
            id: "faithfulness",
            signature: "FaithfulnessMetric",
            summary: "Score grounding against retrieval context.",
            why: "Core RAG quality signal in DeepEval’s catalog.",
            docsUrl: "https://deepeval.com/docs/metrics-faithfulness",
          },
          {
            id: "g-eval",
            signature: "GEval",
            summary: "LLM-as-judge on custom criteria.",
            why: "Subjective quality needs calibrated judges.",
            docsUrl: "https://deepeval.com/docs/metrics-llm-evals",
          },
        ],
      },
      {
        id: "ragas",
        name: "RAGAS",
        summary: "Evaluation toolkit focused on RAG pipelines.",
        docsUrl: "https://docs.ragas.io/",
        docsLabel: "docs.ragas.io",
        calls: [
          {
            id: "faithfulness",
            signature: "faithfulness",
            summary: "Measure answer grounding in contexts.",
            why: "Hallucination control for retrieval apps.",
            docsUrl: "https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/faithfulness/",
          },
          {
            id: "context-precision",
            signature: "context_precision",
            summary: "Rank quality of retrieved chunks.",
            why: "Bad retrieval cannot be fixed by a better prompt alone.",
            docsUrl: "https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/context_precision/",
          },
          {
            id: "answer-relevancy",
            signature: "answer_relevancy",
            summary: "Does the answer address the question?",
            why: "Faithful but off-topic answers still fail users.",
            docsUrl: "https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/answer_relevance/",
          },
        ],
      },
      {
        id: "langsmith",
        name: "LangSmith",
        summary: "Observability and evaluation for LLM applications.",
        docsUrl: "https://docs.smith.langchain.com/",
        docsLabel: "docs.smith.langchain.com",
        calls: [
          {
            id: "tracing",
            signature: "Tracing / runs",
            summary: "Capture model and tool spans.",
            why: "Debug agent failures from the trajectory, not the final string.",
            docsUrl: "https://docs.smith.langchain.com/observability",
          },
          {
            id: "datasets",
            signature: "Datasets & experiments",
            summary: "Version goldens and compare runs.",
            why: "Eval without datasets is anecdotal.",
            docsUrl: "https://docs.smith.langchain.com/evaluation",
          },
          {
            id: "feedback",
            signature: "Feedback / scores",
            summary: "Attach human or auto scores to runs.",
            why: "Closes the loop from production to suite.",
            docsUrl: "https://docs.smith.langchain.com/",
          },
        ],
      },
      {
        id: "rag",
        name: "RAG testing",
        summary: "Retrieve → augment → generate quality strategy.",
        docsUrl: "https://deepeval.com/docs/getting-started-rag",
        docsLabel: "DeepEval RAG guide",
        calls: [
          {
            id: "retrieval",
            signature: "Evaluate retrieval alone",
            summary: "Precision/recall on chunks before generation.",
            why: "Isolate retriever defects from generator defects.",
            docsUrl: "https://deepeval.com/docs/getting-started-rag",
          },
          {
            id: "goldens",
            signature: "Golden datasets",
            summary: "Curate questions with expected contexts/answers.",
            why: "Community RAG courses treat goldens as the real artifact.",
            docsUrl: "https://docs.ragas.io/en/stable/concepts/datasets/",
          },
          {
            id: "abstention",
            signature: "Abstention / no-context behavior",
            summary: "Model should refuse when retrieval is empty.",
            why: "Better than hallucinating from parametric memory.",
            docsUrl: "https://deepeval.com/docs/getting-started-rag",
          },
        ],
      },
      {
        id: "agentic-ai",
        name: "Agentic AI testing",
        summary: "Tool-calling, trajectories, and multi-step agents.",
        docsUrl: "https://deepeval.com/docs/getting-started-agents",
        docsLabel: "DeepEval agents guide",
        calls: [
          {
            id: "tool-use",
            signature: "Tool use / selection metrics",
            summary: "Did the agent pick the right tool and args?",
            why: "Wrong tools look like “smart” answers that are still wrong.",
            docsUrl: "https://deepeval.com/docs/metrics-tool-use",
          },
          {
            id: "trajectory",
            signature: "Trajectory-based evals",
            summary: "Score the full plan → tool → answer path.",
            why: "Final text alone hides looping or unsafe steps.",
            docsUrl: "https://deepeval.com/docs/evaluation-end-to-end-llm-evals",
          },
          {
            id: "task-completion",
            signature: "Task completion",
            summary: "Did the agent finish the user’s goal?",
            why: "Primary product metric for assistants.",
            docsUrl: "https://deepeval.com/docs/getting-started-agents",
          },
        ],
      },
      {
        id: "github-copilot",
        name: "GitHub Copilot",
        summary: "AI pair programmer inside the editor.",
        docsUrl: "https://docs.github.com/en/copilot",
        docsLabel: "docs.github.com/copilot",
        calls: [
          {
            id: "suggestions",
            signature: "Inline suggestions",
            summary: "Accept/adapt generated test stubs carefully.",
            why: "Speed up scaffolding — still review for correctness.",
            docsUrl: "https://docs.github.com/en/copilot/using-github-copilot/getting-code-suggestions-in-your-ide-with-github-copilot",
          },
          {
            id: "chat",
            signature: "Copilot Chat",
            summary: "Ask for locator strategies or refactor plans.",
            why: "Useful for flaky-test triage brainstorming.",
            docsUrl: "https://docs.github.com/en/copilot/using-github-copilot/asking-github-copilot-questions-in-your-ide",
          },
          {
            id: "policies",
            signature: "Org policies & privacy",
            summary: "Know what code is sent where.",
            why: "Enterprise QA must respect data boundaries.",
            docsUrl: "https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization",
          },
        ],
      },
      {
        id: "ms-copilot",
        name: "Microsoft Copilot",
        summary: "AI assistant across Microsoft 365 and Azure workflows.",
        docsUrl: "https://learn.microsoft.com/en-us/copilot/",
        docsLabel: "learn.microsoft.com/copilot",
        calls: [
          {
            id: "prompts",
            signature: "Effective prompting",
            summary: "Frame QA tasks with context and constraints.",
            why: "Better prompts → better draft cases and SQL.",
            docsUrl: "https://learn.microsoft.com/en-us/copilot/overview",
          },
          {
            id: "grounding",
            signature: "Grounding on your data",
            summary: "Understand when answers use tenant data.",
            why: "Validation must know the grounding boundary.",
            docsUrl: "https://learn.microsoft.com/en-us/copilot/",
          },
          {
            id: "responsible",
            signature: "Responsible AI use",
            summary: "Review outputs before merging automation.",
            why: "AI-assisted tests still need human ownership.",
            docsUrl: "https://learn.microsoft.com/en-us/copilot/",
          },
        ],
      },
    ],
  },
  {
    id: "collaboration",
    title: "Collaboration & QA Ops",
    summary: "Defect workflow and quality governance practices.",
    tools: [
      {
        id: "jira",
        name: "JIRA",
        summary: "Issue tracking for Agile delivery and defects.",
        docsUrl: "https://support.atlassian.com/jira-software-cloud/",
        docsLabel: "support.atlassian.com/jira",
        calls: [
          {
            id: "workflows",
            signature: "Issue workflows",
            summary: "Map Open → In Progress → Done (and QA states).",
            why: "STLC visibility depends on honest workflow states.",
            docsUrl: "https://support.atlassian.com/jira-cloud-administration/docs/what-are-issue-workflows/",
          },
          {
            id: "jql",
            signature: "JQL filters",
            summary: "Query defects by sprint, severity, component.",
            why: "Quality reporting is only as good as your queries.",
            docsUrl: "https://support.atlassian.com/jira-software-cloud/docs/use-advanced-search-with-jira-query-language-jql/",
          },
          {
            id: "boards",
            signature: "Scrum / Kanban boards",
            summary: "Track QA work beside development.",
            why: "Agile QA needs the same board discipline as feature work.",
            docsUrl: "https://support.atlassian.com/jira-software-cloud/docs/what-is-a-jira-software-board/",
          },
        ],
      },
      {
        id: "stlc",
        name: "STLC & test strategy",
        summary: "Lifecycle practices: plan, design, execute, report, close.",
        docsUrl: "https://www.istqb.org/",
        docsLabel: "ISTQB / QA practice",
        calls: [
          {
            id: "strategy",
            signature: "Test strategy vs plan",
            summary: "Strategy sets approach; plan sets the release instance.",
            why: "Enterprise programs confuse the two and lose governance.",
            docsUrl: "https://www.istqb.org/",
          },
          {
            id: "defect-mgmt",
            signature: "Defect lifecycle",
            summary: "Severity, priority, reopen rules.",
            why: "Consistent defect data feeds release decisions.",
            docsUrl: "https://support.atlassian.com/jira-software-cloud/docs/what-is-an-issue/",
          },
          {
            id: "traceability",
            signature: "Requirements ↔ cases ↔ defects",
            summary: "Trace coverage for regulated domains.",
            why: "Healthcare/life-sciences QA expects clear trace matrices.",
            docsUrl: "https://www.istqb.org/",
          },
        ],
      },
    ],
  },
] as const;

export function getCategory(id: string): ToolCategory | undefined {
  return toolCategories.find((category) => category.id === id);
}

export function getTool(categoryId: string, toolId: string) {
  const category = getCategory(categoryId);
  if (!category) {
    return undefined;
  }
  const tool = category.tools.find((item) => item.id === toolId);
  if (!tool) {
    return undefined;
  }
  return { category, tool };
}

export function isCategoryId(value: string): value is ToolCategoryId {
  return toolCategories.some((category) => category.id === value);
}
