import type { ToolCategory, ToolCategoryId } from "@/types/tools";

export const toolCategories: readonly ToolCategory[] = [
  {
    id: "ui",
    title: "UI Tools",
    summary: "Playwright page objects, locators, healing, and visual compare.",
    tools: [
      {
        id: "base-page",
        name: "BasePage",
        summary: "Shared open/locator helpers every Sauce Demo page extends.",
        repoPath: "pages/base_page.py",
        calls: [
          {
            id: "open",
            signature: "BasePage.open() -> None",
            summary: "Navigate to the page path and wait for load.",
            why: "Keeps URL construction in one place so tests never hardcode routes.",
            repoPath: "pages/base_page.py",
            relatedTest: "tests/ui/test_login.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "by-test-id",
            signature: "BasePage.by_test_id(test_id: str) -> Locator",
            summary: "Build a Playwright locator from a data-test attribute.",
            why: "User-facing test ids survive restyling better than CSS classes.",
            repoPath: "pages/base_page.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "healable",
            signature: "BasePage.healable(name, selector, description) -> SelfHealingLocator",
            summary: "Wrap a locator so a broken selector can propose replacements.",
            why: "Healing is opt-in per locator — validation still decides pass/fail.",
            repoPath: "pages/base_page.py",
            relatedTest: "tests/ui/healing/test_self_healing.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "expect-loaded",
            signature: "BasePage.expect_loaded() -> None",
            summary: "Assert the page reached a known ready state.",
            why: "Web-first readiness beats sleeps before interacting.",
            repoPath: "pages/base_page.py",
            lessonSlug: "ui-testing",
          },
        ],
      },
      {
        id: "login-page",
        name: "LoginPage",
        summary: "Sauce Demo login form — the first page object most learners run.",
        repoPath: "pages/login_page.py",
        calls: [
          {
            id: "login-as",
            signature: "LoginPage.login_as(username: str, password: str) -> None",
            summary: "Fill credentials and submit the login form.",
            why: "Tests say what user; the page object owns how selectors work.",
            repoPath: "pages/login_page.py",
            relatedTest: "tests/ui/test_login.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "error-text",
            signature: "LoginPage.error_text() -> str",
            summary: "Read the visible login error message.",
            why: "Negative paths need a stable assertion surface, not raw locators in tests.",
            repoPath: "pages/login_page.py",
            relatedTest: "tests/ui/test_login.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "expect-loaded",
            signature: "LoginPage.expect_loaded() -> None",
            summary: "Confirm username/password controls are ready.",
            why: "Guards flaky clicks before the form hydrates.",
            repoPath: "pages/login_page.py",
            lessonSlug: "ui-testing",
          },
        ],
      },
      {
        id: "inventory-page",
        name: "InventoryPage",
        summary: "Product grid: sort, add to cart, read names and prices.",
        repoPath: "pages/inventory_page.py",
        calls: [
          {
            id: "add-to-cart",
            signature: "InventoryPage.add_to_cart(product_name: str) -> None",
            summary: "Add one product by its visible name.",
            why: "Name-based selection matches how a shopper thinks.",
            repoPath: "pages/inventory_page.py",
            relatedTest: "tests/ui/test_checkout_e2e.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "sort-by",
            signature: "InventoryPage.sort_by(option_value: str) -> None",
            summary: "Change the product sort dropdown.",
            why: "Sorting is a pure UI contract with deterministic price/name order.",
            repoPath: "pages/inventory_page.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "prices",
            signature: "InventoryPage.prices() -> list[float]",
            summary: "Collect displayed prices as floats.",
            why: "Numeric lists make sort and cart totals assertable.",
            repoPath: "pages/inventory_page.py",
            lessonSlug: "ui-testing",
          },
        ],
      },
      {
        id: "checkout-page",
        name: "CheckoutPage",
        summary: "Sauce Demo three-step checkout as one page object.",
        repoPath: "pages/checkout_page.py",
        calls: [
          {
            id: "fill-customer-info",
            signature: "CheckoutPage.fill_customer_info(first, last, postal) -> None",
            summary: "Complete step one and continue to overview.",
            why: "One method per checkout step keeps e2e tests readable.",
            repoPath: "pages/checkout_page.py",
            relatedTest: "tests/ui/test_checkout_e2e.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "item-total",
            signature: "CheckoutPage.item_total() -> float",
            summary: "Parse the overview item subtotal.",
            why: "Money assertions belong on the page object, not string splits in tests.",
            repoPath: "pages/checkout_page.py",
            relatedTest: "tests/ui/test_checkout_e2e.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "finish",
            signature: "CheckoutPage.finish() -> None",
            summary: "Place the order from the overview step.",
            why: "Finish is the commit action — keep it explicit for e2e flow.",
            repoPath: "pages/checkout_page.py",
            relatedTest: "tests/ui/test_checkout_e2e.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "total",
            signature: "CheckoutPage.total() -> float",
            summary: "Grand total including tax.",
            why: "Cross-check UI totals against cart math before finishing.",
            repoPath: "pages/checkout_page.py",
            relatedTest: "tests/ui/test_checkout_e2e.py",
            lessonSlug: "ui-testing",
          },
        ],
      },
      {
        id: "self-healing",
        name: "SelfHealingLocator",
        summary: "Propose and validate replacement selectors when POMs break.",
        repoPath: "pages/healing/self_healing.py",
        calls: [
          {
            id: "resolve",
            signature: "SelfHealingLocator.resolve() -> Locator",
            summary: "Current selector → cache → LLM suggest → validated unique match.",
            why: "Healing never trusts the LLM without a live unique-match check.",
            repoPath: "pages/healing/self_healing.py",
            relatedTest: "tests/ui/healing/test_self_healing.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "suggest",
            signature: "LocatorHealer.suggest(description, broken_selector, html) -> list[str]",
            summary: "Propose candidate CSS selectors, best first.",
            why: "Context engineering feeds interactive HTML only — not the whole DOM.",
            repoPath: "pages/healing/self_healing.py",
            relatedTest: "tests/ui/healing/test_self_healing.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "cache-put",
            signature: "HealingCache.put(entry: HealedLocator) -> None",
            summary: "Persist a healed selector for observability.",
            why: "Cache entries are a to-do list to fix the page object — not a silent forever patch.",
            repoPath: "pages/healing/self_healing.py",
            relatedTest: "tests/ui/healing/test_self_healing.py",
            lessonSlug: "ui-testing",
          },
        ],
      },
      {
        id: "visual-comparator",
        name: "VisualComparator",
        summary: "Pixel diff against baselines — pixels decide, not an LLM.",
        repoPath: "visual/comparator.py",
        calls: [
          {
            id: "compare",
            signature: "VisualComparator.compare(name: str, png: bytes) -> VisualResult",
            summary: "Diff a screenshot against a named baseline.",
            why: "Visual regressions need a ratio + artifact, not a prose judgment.",
            repoPath: "visual/comparator.py",
            relatedTest: "tests/ui/visual/",
            lessonSlug: "ui-testing",
          },
          {
            id: "diff-ratio",
            signature: "VisualComparator.diff_ratio(expected, actual) -> tuple[float, Image]",
            summary: "Compute mismatch ratio and a diff image.",
            why: "Thresholds stay calibrated in config, not hardcoded in tests.",
            repoPath: "visual/comparator.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "baseline-path",
            signature: "VisualComparator.baseline_path(name: str) -> Path",
            summary: "Resolve where the golden PNG lives.",
            why: "Baselines are versioned assets — path rules must be stable.",
            repoPath: "visual/comparator.py",
            lessonSlug: "ui-testing",
          },
        ],
      },
    ],
  },
  {
    id: "api",
    title: "API Tools",
    summary: "Typed service clients and pydantic schemas for Restful Booker.",
    tools: [
      {
        id: "base-client",
        name: "BaseClient",
        summary: "Thin HTTP verbs over Playwright APIRequestContext.",
        repoPath: "api/base_client.py",
        calls: [
          {
            id: "get",
            signature: "BaseClient.get(path, *, params=None, headers=None) -> APIResponse",
            summary: "GET with merged default headers.",
            why: "All clients share one transport so auth and base URL stay configured once.",
            repoPath: "api/base_client.py",
            lessonSlug: "api-testing",
          },
          {
            id: "post",
            signature: "BaseClient.post(path, *, data=None, headers=None) -> APIResponse",
            summary: "POST JSON/body to a path.",
            why: "Create flows go through the same header merge as reads.",
            repoPath: "api/base_client.py",
            lessonSlug: "api-testing",
          },
          {
            id: "set-header",
            signature: "BaseClient.set_header(key: str, value: str) -> None",
            summary: "Attach a default header (e.g. Cookie token).",
            why: "Auth is configuration on the client, not copy-paste in every test.",
            repoPath: "api/base_client.py",
            lessonSlug: "api-testing",
          },
        ],
      },
      {
        id: "booking-client",
        name: "BookingClient",
        summary: "CRUD for bookings with pydantic `Booking` bodies.",
        repoPath: "api/booking_client.py",
        calls: [
          {
            id: "create-booking",
            signature: "BookingClient.create_booking(booking: Booking) -> APIResponse",
            summary: "Create a booking from a typed model.",
            why: "A renamed field fails validation even when HTTP status is 200.",
            repoPath: "api/booking_client.py",
            relatedTest: "tests/api/test_booking_crud.py",
            lessonSlug: "api-testing",
          },
          {
            id: "get-booking",
            signature: "BookingClient.get_booking(booking_id: int) -> APIResponse",
            summary: "Fetch one booking by id.",
            why: "Read-after-write is the core contract for CRUD suites.",
            repoPath: "api/booking_client.py",
            relatedTest: "tests/api/test_booking_crud.py",
            lessonSlug: "api-testing",
          },
          {
            id: "partial-update",
            signature: "BookingClient.partial_update(booking_id: int, fields: dict) -> APIResponse",
            summary: "PATCH a subset of booking fields.",
            why: "Partial updates catch optional-field regressions services often break.",
            repoPath: "api/booking_client.py",
            relatedTest: "tests/api/test_booking_crud.py",
            lessonSlug: "api-testing",
          },
          {
            id: "authenticate",
            signature: "BookingClient.authenticate(token: str) -> BookingClient",
            summary: "Attach a token for mutating calls.",
            why: "Fluent auth keeps positive/negative auth tests readable.",
            repoPath: "api/booking_client.py",
            relatedTest: "tests/api/test_auth.py",
            lessonSlug: "api-testing",
          },
        ],
      },
      {
        id: "auth-client",
        name: "AuthClient",
        summary: "Token creation for Restful Booker.",
        repoPath: "api/auth_client.py",
        calls: [
          {
            id: "create-token",
            signature: "AuthClient.create_token(username: str, password: str) -> str",
            summary: "Return a bearer/token string for later clients.",
            why: "Auth is a first-class client — not a raw POST buried in fixtures only.",
            repoPath: "api/auth_client.py",
            relatedTest: "tests/api/test_auth.py",
            lessonSlug: "api-testing",
          },
          {
            id: "create-token-response",
            signature: "AuthClient.create_token_response(username, password) -> APIResponse",
            summary: "Raw response for status/body assertions.",
            why: "Negative auth needs the HTTP envelope, not just a parsed token.",
            repoPath: "api/auth_client.py",
            relatedTest: "tests/api/test_auth.py",
            lessonSlug: "api-testing",
          },
          {
            id: "list-ids",
            signature: "BookingClient.list_ids(**filters) -> APIResponse",
            summary: "List booking ids with optional filters.",
            why: "Filter contracts belong next to CRUD — same client surface.",
            repoPath: "api/booking_client.py",
            relatedTest: "tests/api/test_booking_crud.py",
            lessonSlug: "api-testing",
          },
        ],
      },
    ],
  },
  {
    id: "db",
    title: "DB Tools",
    summary: "SQLite repositories for users, orders, and booking mirrors.",
    tools: [
      {
        id: "base-repository",
        name: "BaseRepository",
        summary: "fetch_one / fetch_all / execute primitives.",
        repoPath: "db/repositories/base_repository.py",
        calls: [
          {
            id: "fetch-one",
            signature: "BaseRepository.fetch_one(sql, params=()) -> dict | None",
            summary: "Run SQL and return one row as a dict.",
            why: "Repositories own SQL; tests assert business facts.",
            repoPath: "db/repositories/base_repository.py",
            lessonSlug: "sql-and-hybrid",
          },
          {
            id: "fetch-all",
            signature: "BaseRepository.fetch_all(sql, params=()) -> list[dict]",
            summary: "Return all matching rows.",
            why: "Integrity checks often need sets, not a single row.",
            repoPath: "db/repositories/base_repository.py",
            lessonSlug: "sql-and-hybrid",
          },
          {
            id: "execute",
            signature: "BaseRepository.execute(sql, params=()) -> int",
            summary: "Mutating SQL with rowcount.",
            why: "Seeds and locks stay behind the same API as reads.",
            repoPath: "db/repositories/base_repository.py",
            lessonSlug: "sql-and-hybrid",
          },
        ],
      },
      {
        id: "user-repository",
        name: "UserRepository",
        summary: "Create, lock, and query demo users.",
        repoPath: "db/repositories/user_repository.py",
        calls: [
          {
            id: "find-by-username",
            signature: "UserRepository.find_by_username(username: str) -> dict | None",
            summary: "Lookup a user row.",
            why: "Hybrid UI+DB tests prove the locked flag the UI claims.",
            repoPath: "db/repositories/user_repository.py",
            relatedTest: "tests/sql/test_user_repository.py",
            lessonSlug: "sql-and-hybrid",
          },
          {
            id: "lock",
            signature: "UserRepository.lock(username: str) -> None",
            summary: "Mark a user locked.",
            why: "Setup for negative login without touching the UI first.",
            repoPath: "db/repositories/user_repository.py",
            relatedTest: "tests/sql/test_user_repository.py",
            lessonSlug: "sql-and-hybrid",
          },
          {
            id: "create",
            signature: "UserRepository.create(username, email, is_locked=False) -> int",
            summary: "Insert a user and return id.",
            why: "Isolated fixtures need deterministic rows per test.",
            repoPath: "db/repositories/user_repository.py",
            relatedTest: "tests/sql/test_user_repository.py",
            lessonSlug: "sql-and-hybrid",
          },
        ],
      },
      {
        id: "order-repository",
        name: "OrderRepository",
        summary: "Orders, totals, and data-integrity queries.",
        repoPath: "db/repositories/order_repository.py",
        calls: [
          {
            id: "orphan-order-items",
            signature: "OrderRepository.orphan_order_items() -> list[dict]",
            summary: "Find order lines without a parent order.",
            why: "Integrity tests catch FK drift before production invoices do.",
            repoPath: "db/repositories/order_repository.py",
            relatedTest: "tests/sql/test_data_integrity.py",
            lessonSlug: "sql-and-hybrid",
          },
          {
            id: "price-mismatches",
            signature: "OrderRepository.price_mismatches() -> list[dict]",
            summary: "Lines whose stored price disagrees with catalog.",
            why: "Money bugs are SQL bugs — assert them in the repository layer.",
            repoPath: "db/repositories/order_repository.py",
            relatedTest: "tests/sql/test_data_integrity.py",
            lessonSlug: "sql-and-hybrid",
          },
          {
            id: "order-total",
            signature: "OrderRepository.order_total(order_id: int) -> float",
            summary: "Sum line items for one order.",
            why: "Cross-check UI cart totals against the database.",
            repoPath: "db/repositories/order_repository.py",
            lessonSlug: "sql-and-hybrid",
          },
        ],
      },
      {
        id: "booking-repository",
        name: "BookingRepository",
        summary: "Mirror API bookings into SQL for hybrid API↔DB checks.",
        repoPath: "db/repositories/booking_repository.py",
        calls: [
          {
            id: "save",
            signature: "BookingRepository.save(booking_id: int, booking: Booking) -> None",
            summary: "Insert a booking under the id the API assigned.",
            why: "Hybrid tests prove the API write landed in the database shape you expect.",
            repoPath: "db/repositories/booking_repository.py",
            relatedTest: "tests/hybrid/test_api_to_db.py",
            lessonSlug: "sql-and-hybrid",
          },
          {
            id: "find",
            signature: "BookingRepository.find(booking_id: int) -> dict | None",
            summary: "Read the stored booking row.",
            why: "Read-after-API-write is the hybrid contract.",
            repoPath: "db/repositories/booking_repository.py",
            relatedTest: "tests/hybrid/test_api_to_db.py",
            lessonSlug: "sql-and-hybrid",
          },
          {
            id: "dates-isoformat",
            signature: "booking.bookingdates.checkin/checkout.isoformat()",
            summary: "Persist checkin/checkout as ISO dates in SQL.",
            why: "Date formats drift between API JSON and SQL — assert them explicitly.",
            repoPath: "db/repositories/booking_repository.py",
            relatedTest: "tests/hybrid/test_api_to_db.py",
            lessonSlug: "sql-and-hybrid",
          },
        ],
      },
    ],
  },
  {
    id: "ai-evals",
    title: "AI Evals",
    summary: "Judges, metric factory, deterministic gates — calibrate before gating CI.",
    tools: [
      {
        id: "judge",
        name: "Judge helpers",
        summary: "Local Ollama judges for DeepEval and Ragas (no paid API).",
        repoPath: "ai/evaluators/judge.py",
        calls: [
          {
            id: "deepeval-judge",
            signature: "deepeval_judge(model: str, ollama_host: str) -> OllamaModel",
            summary: "DeepEval judge at temperature 0 for repeatable verdicts.",
            why: "The judge must not be the model under test — swap via JUDGE_MODEL.",
            repoPath: "ai/evaluators/judge.py",
            relatedTest: "tests/ai/conftest.py",
            lessonSlug: "judges-and-calibration",
          },
          {
            id: "ragas-judge",
            signature: "ragas_judge(model: str, ollama_host: str)",
            summary: "Ragas-compatible judge wrapper around ChatOllama.",
            why: "Ragas needs reliable structured JSON — prefer ≥7B; 3B often parse-fails.",
            repoPath: "ai/evaluators/judge.py",
            lessonSlug: "judges-and-calibration",
          },
          {
            id: "strong-judge-factory",
            signature: "MetricFactory(deepeval_judge(strong_judge_model, host), threshold=...)",
            summary: "Wire a stronger judge into MetricFactory for hard metrics.",
            why: "Calibration: eight metrics here need a stronger judge before gating CI.",
            repoPath: "ai/evaluators/factory.py",
            relatedTest: "tests/ai/conftest.py",
            lessonSlug: "judges-and-calibration",
          },
        ],
      },
      {
        id: "metric-factory",
        name: "MetricFactory",
        summary: "Build DeepEval metrics with shared judge + thresholds.",
        repoPath: "ai/evaluators/factory.py",
        calls: [
          {
            id: "faithfulness",
            signature: "MetricFactory.faithfulness(threshold=None) -> FaithfulnessMetric",
            summary: "RAG faithfulness against retrieval_context.",
            why: "Community RAG suites always start here — grounded answers only.",
            repoPath: "ai/evaluators/factory.py",
            relatedTest: "tests/ai/rag/",
            lessonSlug: "judges-and-calibration",
          },
          {
            id: "answer-relevancy",
            signature: "MetricFactory.answer_relevancy(threshold=None) -> AnswerRelevancyMetric",
            summary: "Does the answer address the question?",
            why: "Faithful but off-topic answers still fail product quality.",
            repoPath: "ai/evaluators/factory.py",
            lessonSlug: "evaluating-llms",
          },
          {
            id: "correctness",
            signature: "MetricFactory.correctness(threshold=None) -> GEval",
            summary: "G-Eval rubric for factual correctness.",
            why: "Custom criteria need LLM-as-judge — after calibration.",
            repoPath: "ai/evaluators/factory.py",
            lessonSlug: "judges-and-calibration",
          },
          {
            id: "toxicity",
            signature: "MetricFactory.toxicity(threshold=None) -> ToxicityMetric",
            summary: "Safety ceiling metric.",
            why: "Safety scores are ceilings, not floors — invert them and CI lies.",
            repoPath: "ai/evaluators/factory.py",
            lessonSlug: "red-teaming",
          },
        ],
      },
      {
        id: "deterministic",
        name: "Deterministic evaluators",
        summary: "No-LLM gates: refusal, canary, JSON schema, word limits.",
        repoPath: "ai/evaluators/deterministic.py",
        calls: [
          {
            id: "refusal",
            signature: "RefusalEvaluator(expect_refusal=True).evaluate(test_case)",
            summary: "Check the model refused (or failed to).",
            why: "Safety refusals should not depend on a flaky judge.",
            repoPath: "ai/evaluators/deterministic.py",
            lessonSlug: "red-teaming",
          },
          {
            id: "json-schema",
            signature: "JsonSchemaEvaluator(schema).evaluate(test_case)",
            summary: "Parse actual_output against a pydantic schema.",
            why: "Structured outputs fail closed on shape before semantics.",
            repoPath: "ai/evaluators/deterministic.py",
            lessonSlug: "evaluating-llms",
          },
          {
            id: "canary",
            signature: "CanaryLeakEvaluator(canary).evaluate(test_case)",
            summary: "Detect a planted secret string in the output.",
            why: "Prompt-injection drills need a crisp pass/fail signal.",
            repoPath: "ai/evaluators/deterministic.py",
            lessonSlug: "red-teaming",
          },
        ],
      },
      {
        id: "conversation-eval",
        name: "ConversationFactsEvaluator",
        summary: "Multi-turn fact retention checks.",
        repoPath: "ai/evaluators/conversation.py",
        calls: [
          {
            id: "measure",
            signature: "ConversationFactsEvaluator.measure(test_case) -> float",
            summary: "Score whether required facts appear in a turn.",
            why: "Chatbots fail across turns — single-shot metrics miss that.",
            repoPath: "ai/evaluators/conversation.py",
            relatedTest: "tests/ai/conversation/",
            lessonSlug: "evaluating-llms",
          },
          {
            id: "is-successful",
            signature: "ConversationFactsEvaluator.is_successful() -> bool",
            summary: "Thresholded pass after measure.",
            why: "DeepEval-style API: measure then gate.",
            repoPath: "ai/evaluators/conversation.py",
            lessonSlug: "evaluating-llms",
          },
          {
            id: "init-facts",
            signature: "ConversationFactsEvaluator(facts, turn=-1, threshold=1.0)",
            summary: "Configure which facts must stick on which turn.",
            why: "Goldens belong in the evaluator constructor, not buried in asserts.",
            repoPath: "ai/evaluators/conversation.py",
            lessonSlug: "evaluating-llms",
          },
        ],
      },
    ],
  },
  {
    id: "rag",
    title: "RAG & Search",
    summary: "Retrieve → augment → generate on a fictional store policy corpus.",
    tools: [
      {
        id: "rag-pipeline",
        name: "RagPipeline",
        summary: "End-to-end answer with contexts for faithfulness scoring.",
        repoPath: "ai/search/rag.py",
        calls: [
          {
            id: "answer",
            signature: "RagPipeline.answer(question: str) -> RagAnswer",
            summary: "Retrieve passages and generate an answer.",
            why: "One call produces both text and contexts evals need.",
            repoPath: "ai/search/rag.py",
            relatedTest: "tests/ai/rag/",
            lessonSlug: "rag",
          },
          {
            id: "contexts",
            signature: "RagAnswer.contexts -> list[str]",
            summary: "Retrieved passage texts for the judge.",
            why: "Faithfulness is undefined without retrieval_context.",
            repoPath: "ai/search/rag.py",
            lessonSlug: "rag",
          },
          {
            id: "document-ids",
            signature: "RagAnswer.document_ids -> list[str]",
            summary: "Ids of documents that supported the answer.",
            why: "Precision/recall metrics need identity, not only text.",
            repoPath: "ai/search/rag.py",
            lessonSlug: "rag",
          },
        ],
      },
      {
        id: "retrievers",
        name: "Retrievers",
        summary: "Corpus lookup used before generation.",
        repoPath: "ai/search/retrievers.py",
        calls: [
          {
            id: "retrieve",
            signature: "Retriever.retrieve(query: str, k: int) -> list[Passage]",
            summary: "Top-k passages for a query.",
            why: "Test retrieval alone before blaming the generator.",
            repoPath: "ai/search/retrievers.py",
            relatedTest: "tests/ai/search/",
            lessonSlug: "ai-search",
          },
          {
            id: "min-score",
            signature: "RagPipeline(..., min_score: float | None)",
            summary: "Drop weak matches before prompting.",
            why: "Abstention beats hallucinating from junk context.",
            repoPath: "ai/search/rag.py",
            lessonSlug: "rag",
          },
          {
            id: "corpus",
            signature: "ai/search/corpus.json",
            summary: "Fictional store policy documents the model cannot memorize from training.",
            why: "Grounding evals need a private corpus — community RAG courses stress this.",
            repoPath: "ai/search/corpus.json",
            lessonSlug: "rag",
          },
        ],
      },
    ],
  },
  {
    id: "agents-mcp",
    title: "Agents & MCP",
    summary: "Tool-using shop assistant and the store MCP server contract.",
    tools: [
      {
        id: "store-mcp",
        name: "Store MCP server",
        summary: "list_products, get_price, search_policies — contract-testable tools.",
        repoPath: "apps/store_mcp/server.py",
        calls: [
          {
            id: "list-products",
            signature: "list_products() -> list[Product]",
            summary: "MCP tool: catalog listing.",
            why: "Tool discovery + schema is the first MCP contract.",
            repoPath: "apps/store_mcp/server.py",
            relatedTest: "tests/ai/mcp/",
            lessonSlug: "testing-mcp-servers",
          },
          {
            id: "get-price",
            signature: "get_price(product: str) -> Product",
            summary: "MCP tool: price lookup by product name.",
            why: "Argument correctness is what MCP-Use metrics judge.",
            repoPath: "apps/store_mcp/server.py",
            relatedTest: "tests/ai/mcp/",
            lessonSlug: "how-mcp-works",
          },
          {
            id: "search-policies",
            signature: "search_policies(query: str, k: int = 3) -> list[Passage]",
            summary: "MCP tool: policy search for grounded answers.",
            why: "Agents should call this instead of inventing return policy.",
            repoPath: "apps/store_mcp/server.py",
            relatedTest: "tests/ai/mcp/",
            lessonSlug: "playwright-mcp",
          },
        ],
      },
      {
        id: "shop-assistant",
        name: "Shop assistant agent",
        summary: "Tool loop over store capabilities (text + LangGraph variants).",
        repoPath: "apps/shop_assistant/agent.py",
        calls: [
          {
            id: "run-turn",
            signature: "agent turn: user message → tool calls → final text",
            summary: "Drive one assistant turn and capture the trajectory.",
            why: "Agent quality is path + answer — community trajectory evals agree.",
            repoPath: "apps/shop_assistant/agent.py",
            relatedTest: "tests/ai/agent/",
            lessonSlug: "testing-agents",
          },
          {
            id: "shared-tools",
            signature: "apps/shop_assistant/shared.py tool bindings",
            summary: "Shared tool definitions reused by text and LangGraph agents.",
            why: "One contract, two runtimes — less drift between demos.",
            repoPath: "apps/shop_assistant/shared.py",
            lessonSlug: "building-agents",
          },
          {
            id: "langgraph",
            signature: "apps/shop_assistant/langgraph_agent.py",
            summary: "Graph-based agent variant for the same shop task.",
            why: "Learn the same tools through a second orchestration style.",
            repoPath: "apps/shop_assistant/langgraph_agent.py",
            relatedTest: "tests/ai/langgraph/",
            lessonSlug: "langgraph",
          },
        ],
      },
    ],
  },
  {
    id: "mobile",
    title: "Mobile Tools",
    summary: "Appium screen objects and driver factory (optional suite).",
    tools: [
      {
        id: "base-screen",
        name: "BaseScreen",
        summary: "find / tap / type helpers for mobile screens.",
        repoPath: "mobile/screens/base_screen.py",
        calls: [
          {
            id: "tap",
            signature: "BaseScreen.tap(locator) -> None",
            summary: "Tap a mobile element.",
            why: "Same page-object idea as UI — actions live on the screen.",
            repoPath: "mobile/screens/base_screen.py",
            relatedTest: "tests/mobile/",
            lessonSlug: "ui-testing",
          },
          {
            id: "type",
            signature: "BaseScreen.type(locator, text: str) -> None",
            summary: "Type into a field.",
            why: "Keeps waits/timeouts inside the screen object.",
            repoPath: "mobile/screens/base_screen.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "is-visible",
            signature: "BaseScreen.is_visible(locator) -> bool",
            summary: "Visibility probe with timeout.",
            why: "Assertions should not reach into raw WebDriver calls.",
            repoPath: "mobile/screens/base_screen.py",
            lessonSlug: "ui-testing",
          },
        ],
      },
      {
        id: "driver-factory",
        name: "Driver factory",
        summary: "Lazy Appium driver construction for optional CI.",
        repoPath: "mobile/driver_factory.py",
        calls: [
          {
            id: "create-driver",
            signature: "create / get Appium driver from settings",
            summary: "Build a driver only when mobile tests run.",
            why: "Hermetic PR CI must not import Selenium/Appium at collection time.",
            repoPath: "mobile/driver_factory.py",
            relatedTest: "tests/mobile/",
            lessonSlug: "ci-cd",
          },
          {
            id: "rotate",
            signature: "BaseScreen.rotate(orientation: str) -> None",
            summary: "Rotate device orientation.",
            why: "Layout bugs often appear only in landscape.",
            repoPath: "mobile/screens/base_screen.py",
            lessonSlug: "ui-testing",
          },
          {
            id: "find-all",
            signature: "BaseScreen.find_all(locator) -> list",
            summary: "Collect matching elements.",
            why: "List length asserts map cleanly to inventory-style screens.",
            repoPath: "mobile/screens/base_screen.py",
            lessonSlug: "ui-testing",
          },
        ],
      },
    ],
  },
] as const;

export function getCategory(id: string): ToolCategory | undefined {
  return toolCategories.find((category) => category.id === id);
}

export function getTool(
  categoryId: string,
  toolId: string,
): { category: ToolCategory; tool: AcademyToolSafe } | undefined {
  const category = getCategory(categoryId);
  if (!category) {
    return undefined;
  }
  const tool = category.tools.find((item) => item.id === toolId);
  if (!tool) {
    return undefined;
  }
  return { category, tool };
}

type AcademyToolSafe = ToolCategory["tools"][number];

export function isCategoryId(value: string): value is ToolCategoryId {
  return toolCategories.some((category) => category.id === value);
}
