import type { LearningCall } from "@/types/tools";

/** Compact LearningCall factory for the expanded on-site API catalogs. */
function api(
  id: string,
  signature: string,
  summary: string,
  why: string,
  docsUrl: string,
): LearningCall {
  return { id, signature, summary, why, docsUrl };
}

/**
 * Full function / concept catalogs taught on-site (not docs redirects).
 * Merged over the thin starter `calls` arrays in `tools-catalog.ts`.
 */
export const TOOL_API_CALLS: Readonly<Record<string, readonly LearningCall[]>> = {
  playwright: [
    api("goto", "page.goto(url, options?)", "Navigate and wait for a load state.", "Every UI journey starts with a controlled navigation.", "https://playwright.dev/docs/api/class-page#page-goto"),
    api("get-by-role", "page.getByRole(role, options)", "Locate by accessibility role and accessible name.", "User-facing locators survive redesigns better than CSS.", "https://playwright.dev/docs/locators#locate-by-role"),
    api("get-by-label", "page.getByLabel(text)", "Locate form controls by associated label text.", "Forms should be tested the way users read them.", "https://playwright.dev/docs/locators#locate-by-label"),
    api("get-by-test-id", "page.getByTestId(testId)", "Locate via data-testid (or configured test id attribute).", "Stable hooks for components without good accessible names.", "https://playwright.dev/docs/locators#locate-by-test-id"),
    api("locator-actions", "locator.click() / fill() / press()", "Auto-waiting actions on locators.", "Actions retry until actionable — no manual sleeps.", "https://playwright.dev/docs/input"),
    api("expect", "expect(locator).toBeVisible()", "Web-first assertions with auto-retry.", "Assertions wait for the UI to settle instead of racing.", "https://playwright.dev/docs/test-assertions"),
    api("expect-soft", "expect.soft(locator)...", "Collect multiple failures in one test.", "Useful for form validation matrices without early abort.", "https://playwright.dev/docs/test-assertions#soft-assertions"),
    api("expect-poll", "expect.poll(fn)", "Retry a custom async probe until it matches.", "Bridge non-DOM signals (API, metrics) into web-first style.", "https://playwright.dev/docs/test-assertions#expectpoll"),
    api("wait-for-url", "page.waitForURL(url)", "Wait until navigation reaches a URL pattern.", "Assert post-submit redirects without sleeps.", "https://playwright.dev/docs/api/class-page#page-wait-for-url"),
    api("wait-for-response", "page.waitForResponse(predicate)", "Synchronize UI with a specific network response.", "Stable checkout/search flows need request pairing.", "https://playwright.dev/docs/network#network-events"),
    api("route", "page.route(url, handler)", "Mock, abort, or modify network traffic.", "Deterministic UI tests when backends are slow or flaky.", "https://playwright.dev/docs/network#network-mocking"),
    api("request", "request.get/post (APIRequestContext)", "First-class API testing beside the browser.", "Seed data and assert contracts without a UI detour.", "https://playwright.dev/docs/api-testing"),
    api("storage-state", "context.storageState()", "Persist cookies/localStorage for auth reuse.", "Login once; reuse state across projects for speed.", "https://playwright.dev/docs/auth"),
    api("fixtures", "test.extend({ ... })", "Custom fixtures for pages, users, and APIs.", "Share arrange/act plumbing without globals.", "https://playwright.dev/docs/test-fixtures"),
    api("test-step", "test.step(title, body)", "Named steps in the report/trace.", "Readable traces for long journeys and failures.", "https://playwright.dev/docs/api/class-test#test-step"),
    api("frame-locator", "page.frameLocator(selector)", "Pierce into iframes with a locator chain.", "Payment widgets and legacy embeds live in frames.", "https://playwright.dev/docs/frames"),
    api("file-upload", "locator.setInputFiles(files)", "Attach files to <input type=file>.", "Uploads are common regression hotspots.", "https://playwright.dev/docs/api/class-locator#locator-set-input-files"),
    api("download", "page.waitForEvent('download')", "Capture and assert file downloads.", "Export/report features need binary evidence.", "https://playwright.dev/docs/downloads"),
    api("dialog", "page.on('dialog') / page.once('dialog')", "Accept, dismiss, or assert native dialogs.", "Confirm prompts break flows if ignored.", "https://playwright.dev/docs/dialogs"),
    api("screenshot", "page.screenshot() / expect().toHaveScreenshot()", "Capture visual evidence or visual regression.", "Catch CSS regressions the DOM assertions miss.", "https://playwright.dev/docs/screenshots"),
    api("trace", "trace: 'on-first-retry'", "Record DOM/network/screenshots for failures.", "Debug CI flakes without re-running locally blind.", "https://playwright.dev/docs/trace-viewer"),
    api("evaluate", "page.evaluate(fn)", "Run JS in the page context.", "Escape hatch for app-internal state checks.", "https://playwright.dev/docs/evaluating"),
    api("viewport", "page.setViewportSize / devices", "Emulate desktop and mobile viewports.", "Responsive bugs need explicit device projects.", "https://playwright.dev/docs/emulation"),
    api("parallel", "fullyParallel / workers / projects", "Scale suites across browsers and shards.", "CI time is a product requirement for QA.", "https://playwright.dev/docs/test-parallel"),
  ],

  selenium: [
    api("get", "driver.get(url)", "Load a URL in the WebDriver session.", "Core navigation entry point.", "https://www.selenium.dev/documentation/webdriver/interactions/navigation/"),
    api("find-element", "driver.findElement(By...)", "Locate a single element.", "Foundation of page objects.", "https://www.selenium.dev/documentation/webdriver/elements/locators/"),
    api("find-elements", "driver.findElements(By...)", "Locate a collection of elements.", "Lists, tables, and empty-state checks.", "https://www.selenium.dev/documentation/webdriver/elements/locators/"),
    api("waits", "WebDriverWait / ExpectedConditions", "Explicit waits for conditions.", "Replace Thread.sleep with conditions.", "https://www.selenium.dev/documentation/webdriver/waits/"),
    api("actions", "Actions / ActionChains", "Mouse and keyboard sequences.", "Hover menus and drag-drop need action chains.", "https://www.selenium.dev/documentation/webdriver/actions_api/"),
    api("select", "Select(element)", "Interact with <select> controls.", "Native dropdowns need the Select helper.", "https://www.selenium.dev/documentation/webdriver/elements/select_lists/"),
    api("alerts", "driver.switchTo().alert()", "Handle browser alerts/prompts.", "Native dialogs block the next command.", "https://www.selenium.dev/documentation/webdriver/interactions/alerts/"),
    api("frames", "driver.switchTo().frame(...)", "Enter and leave iframes.", "Legacy apps still embed critical UI in frames.", "https://www.selenium.dev/documentation/webdriver/interactions/frames/"),
    api("windows", "driver.switchTo().window(handle)", "Switch browser tabs/windows.", "OAuth and print flows open new windows.", "https://www.selenium.dev/documentation/webdriver/interactions/windows/"),
    api("cookies", "driver.manage().getCookies()", "Read/write cookie state.", "Seed auth without UI login every test.", "https://www.selenium.dev/documentation/webdriver/interactions/cookies/"),
    api("javascript", "driver.executeScript(...)", "Run JS in the page.", "Scroll into view and read computed state.", "https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/"),
    api("screenshot", "driver.getScreenshotAs(...)", "Capture failure screenshots.", "Attach evidence to CI artifacts.", "https://www.selenium.dev/documentation/webdriver/browsers/chrome/"),
  ],

  cypress: [
    api("visit", "cy.visit(url)", "Open an application URL.", "Starts every Cypress spec.", "https://docs.cypress.io/api/commands/visit"),
    api("get", "cy.get(selector)", "Query the DOM with retries.", "Commands retry until they pass.", "https://docs.cypress.io/api/commands/get"),
    api("contains", "cy.contains(text)", "Find elements by text content.", "User-visible copy is a strong locator.", "https://docs.cypress.io/api/commands/contains"),
    api("click-type", "cy.click() / cy.type()", "Interact with elements.", "Actionability checks reduce flakes.", "https://docs.cypress.io/api/commands/click"),
    api("should", "cy.should(assertion)", "Retryable assertions.", "Chain assertions on the subject.", "https://docs.cypress.io/guides/references/assertions"),
    api("intercept", "cy.intercept(method, url)", "Stub or spy on network.", "Stable UI without live backends.", "https://docs.cypress.io/api/commands/intercept"),
    api("request", "cy.request(options)", "Direct HTTP from the test runner.", "Seed data faster than the UI.", "https://docs.cypress.io/api/commands/request"),
    api("fixture", "cy.fixture(path)", "Load static test data files.", "Keep payloads out of specs.", "https://docs.cypress.io/api/commands/fixture"),
    api("session", "cy.session(id, setup)", "Cache auth/setup across specs.", "Cut login tax in large suites.", "https://docs.cypress.io/api/commands/session"),
    api("within", "cy.within(() => ...)", "Scope commands to a subtree.", "Avoid brittle global selectors.", "https://docs.cypress.io/api/commands/within"),
    api("clock-tick", "cy.clock() / cy.tick()", "Control timers in the app.", "Test expiry/toasts without waiting.", "https://docs.cypress.io/api/commands/clock"),
    api("custom-commands", "Cypress.Commands.add(...)", "Share reusable commands.", "Encode product workflows once.", "https://docs.cypress.io/api/cypress-api/custom-commands"),
  ],

  accelq: [
    api("actions", "Action logic / scenarios", "Compose reusable business actions.", "Scale via action libraries.", "https://support.accelq.com/"),
    api("data-driven", "Data-driven test design", "Parameterize scenarios with external data.", "Coverage without duplicating flows.", "https://support.accelq.com/"),
    api("ci-hooks", "CI/CD execution hooks", "Run suites from pipeline agents.", "Gate releases like code tests.", "https://support.accelq.com/"),
    api("object-repo", "Shared object repository", "Centralize application object maps.", "One locator fix updates many tests.", "https://support.accelq.com/"),
    api("api-steps", "API steps in scenarios", "Mix UI and API in one scenario.", "Hybrid journeys match real systems.", "https://support.accelq.com/"),
    api("reporting", "Execution reports / evidence", "Publish run evidence for stakeholders.", "Audits need pass/fail with screenshots.", "https://support.accelq.com/"),
    api("environments", "Environment profiles", "Point suites at QA/UAT/prod-like.", "Same scenario, different endpoints.", "https://support.accelq.com/"),
    api("modular", "Modular test design", "Compose scenarios from actions.", "Avoid monolithic recorded scripts.", "https://support.accelq.com/"),
  ],

  cucumber: [
    api("feature", "Feature / Scenario (Gherkin)", "Describe behavior in business language.", "Shared acceptance language.", "https://cucumber.io/docs/gherkin/reference/"),
    api("scenario-outline", "Scenario Outline + Examples", "Data-drive scenarios from tables.", "One scenario, many inputs.", "https://cucumber.io/docs/gherkin/reference/#scenario-outline"),
    api("step-defs", "Step definitions", "Bind Gherkin to automation code.", "Readable specs stay executable.", "https://cucumber.io/docs/cucumber/step-definitions/"),
    api("hooks", "Before / After hooks", "Setup and teardown around scenarios.", "Isolate state cleanly.", "https://cucumber.io/docs/cucumber/api/#hooks"),
    api("tags", "@smoke / @wip tags", "Select subsets of scenarios.", "PR vs nightly scope control.", "https://cucumber.io/docs/cucumber/api/#tags"),
    api("datatable", "Data tables in steps", "Pass structured data into steps.", "Forms and matrices stay readable.", "https://cucumber.io/docs/gherkin/reference/#data-tables"),
    api("background", "Background", "Shared Given steps per feature.", "DRY without hiding intent.", "https://cucumber.io/docs/gherkin/reference/#background"),
    api("world", "World / dependency injection", "Share context across steps.", "Avoid global mutable state.", "https://cucumber.io/docs/cucumber/state/"),
    api("reports", "JSON / HTML reports", "Publish BDD results to CI.", "Stakeholders read features, not logs.", "https://cucumber.io/docs/cucumber/reporting/"),
  ],

  appium: [
    api("create-session", "driver = remote(capabilities)", "Start a session with device caps.", "Caps define platform and engine.", "https://appium.io/docs/en/latest/guides/caps/"),
    api("find-element", "driver.findElement / $()", "Locate mobile elements.", "Accessibility ids beat absolute XPath.", "https://appium.io/docs/en/latest/guides/migrating-1-to-2/"),
    api("gestures", "mobile gestures / W3C actions", "Tap, swipe, pinch sequences.", "Mobile UX needs more than click.", "https://appium.io/docs/en/latest/guides/actions/"),
    api("contexts", "NATIVE_APP / WEBVIEW", "Switch between native and webviews.", "Hybrid apps require context hops.", "https://appium.io/docs/en/latest/guides/context/"),
    api("waits", "Explicit waits / waitUntil", "Wait for mobile UI readiness.", "Animations make fixed sleeps fail.", "https://appium.io/docs/en/latest/guides/waiting/"),
    api("device-lock", "lock / unlock / background", "Control device lifecycle.", "Interruptions are real user paths.", "https://appium.io/docs/en/latest/commands/device/"),
    api("notifications", "openNotifications / push", "Assert system notifications.", "OTP and push flows need OS UI.", "https://appium.io/docs/en/latest/commands/device/"),
    api("page-source", "driver.pageSource", "Dump the UI tree for debugging.", "Inspect hierarchies when locators fail.", "https://appium.io/docs/en/latest/commands/session/"),
    api("parallel-devices", "device farm / parallel sessions", "Scale across emulators/devices.", "Device time is the bottleneck.", "https://appium.io/docs/en/latest/guides/migrating-1-to-2/"),
  ],

  squish: [
    api("startapp", "startApplication(...)", "Launch the AUT under Squish.", "Attach to Qt/desktop/embedded apps.", "https://doc.qt.io/squish/"),
    api("object-map", "objectMap / names", "Stable symbolic object names.", "Recorded names need curation.", "https://doc.qt.io/squish/"),
    api("click-type", "clickButton / typeText", "Interact with GUI controls.", "Scripted interactions for desktop GUIs.", "https://doc.qt.io/squish/"),
    api("verifications", "test.compare / VP points", "Assert properties and visuals.", "Verification points catch GUI drift.", "https://doc.qt.io/squish/"),
    api("event-handlers", "installEventHandler", "React to unexpected dialogs.", "Keep suites resilient to popups.", "https://doc.qt.io/squish/"),
    api("bdd", "feature files in Squish", "BDD style for GUI suites.", "Share intent with stakeholders.", "https://doc.qt.io/squish/"),
    api("datasets", "testData / tables", "Data-drive GUI scenarios.", "Cover permutations without clones.", "https://doc.qt.io/squish/"),
    api("ci", "squishrunner / XML reports", "Headless CI execution.", "Desktop GUI still gates releases.", "https://doc.qt.io/squish/"),
  ],

  pytest: [
    api("test-fn", "def test_*(...)", "Collect plain test functions.", "Zero ceremony unit/API tests.", "https://docs.pytest.org/en/stable/how-to/assert.html"),
    api("fixtures", "@pytest.fixture", "Inject setup via fixtures.", "Compose arrange steps without inheritance.", "https://docs.pytest.org/en/stable/fixture.html"),
    api("parametrize", "@pytest.mark.parametrize", "Run one test with many inputs.", "Table-driven coverage.", "https://docs.pytest.org/en/stable/how-to/parametrize.html"),
    api("markers", "@pytest.mark.*", "Tag and select tests.", "PR vs nightly selection.", "https://docs.pytest.org/en/stable/example/markers.html"),
    api("raises", "pytest.raises(...)", "Assert exceptions.", "Negative paths are first-class.", "https://docs.pytest.org/en/stable/how-to/assert.html#assertions-about-expected-exceptions"),
    api("approx", "pytest.approx(...)", "Compare floats safely.", "Metrics and money need tolerances.", "https://docs.pytest.org/en/stable/reference/reference.html#pytest-approx"),
    api("tmp-path", "tmp_path fixture", "Isolated temp directories.", "File I/O tests stay hermetic.", "https://docs.pytest.org/en/stable/how-to/tmp_path.html"),
    api("monkeypatch", "monkeypatch", "Patch env and attributes.", "Avoid real network in unit tests.", "https://docs.pytest.org/en/stable/how-to/monkeypatch.html"),
    api("caplog", "caplog fixture", "Assert log output.", "Observability is a contract too.", "https://docs.pytest.org/en/stable/how-to/logging.html"),
    api("xdist", "pytest -n auto", "Parallelize with xdist.", "Cut suite wall-clock time.", "https://pytest-xdist.readthedocs.io/"),
    api("plugins", "conftest.py hooks", "Extend collection and reporting.", "Org-wide standards live in plugins.", "https://docs.pytest.org/en/stable/how-to/writing_plugins.html"),
  ],

  testng: [
    api("test-anno", "@Test", "Declare a TestNG test method.", "Core annotation for suites.", "https://testng.org/doc/documentation-main.html"),
    api("dataprovider", "@DataProvider", "Feed rows into @Test methods.", "Data-driven Java tests.", "https://testng.org/doc/documentation-main.html#parameters-dataproviders"),
    api("before-after", "@BeforeMethod / @AfterMethod", "Lifecycle hooks per method/class.", "Reset state between tests.", "https://testng.org/doc/documentation-main.html#annotations"),
    api("groups", "groups = {...}", "Partition suites by group.", "Smoke vs regression selection.", "https://testng.org/doc/documentation-main.html#test-groups"),
    api("depends", "dependsOnMethods", "Order dependent tests carefully.", "Use sparingly — prefer isolation.", "https://testng.org/doc/documentation-main.html#dependent-methods"),
    api("parallel", "parallel=methods|tests", "Configure parallel execution.", "Suite XML controls concurrency.", "https://testng.org/doc/documentation-main.html#parallel-running"),
    api("asserts", "Assert.assertEquals", "Hard assertions in tests.", "Fail fast on contract breaks.", "https://testng.org/doc/documentation-main.html"),
    api("softassert", "SoftAssert", "Collect multiple assertion failures.", "Form matrices without aborting early.", "https://testng.org/doc/documentation-main.html"),
    api("listeners", "ITestListener", "Hook into run lifecycle.", "Custom reporting and retries.", "https://testng.org/doc/documentation-main.html#testng-listeners"),
  ],

  nunit: [
    api("test", "[Test]", "Mark a test method.", "NUnit discovery entry.", "https://docs.nunit.org/articles/nunit/writing-tests/attributes/test.html"),
    api("testcase", "[TestCase(...)]", "Inline parameterized cases.", "Compact data-driven tests.", "https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html"),
    api("testcasesource", "[TestCaseSource]", "Externalize case data.", "Share tables across fixtures.", "https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html"),
    api("setup-teardown", "[SetUp] / [TearDown]", "Per-test lifecycle.", "Fresh state each method.", "https://docs.nunit.org/articles/nunit/writing-tests/attributes/setup.html"),
    api("onetimesetup", "[OneTimeSetUp]", "Fixture-level expensive setup.", "Login or DB seed once.", "https://docs.nunit.org/articles/nunit/writing-tests/attributes/onetimesetup.html"),
    api("assert-that", "Assert.That(actual, constraint)", "Constraint-based asserts.", "Readable failure messages.", "https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html"),
    api("category", "[Category]", "Tag tests for filters.", "CI selects by category.", "https://docs.nunit.org/articles/nunit/writing-tests/attributes/category.html"),
    api("parallelizable", "[Parallelizable]", "Opt into parallel runs.", "Speed .NET suites safely.", "https://docs.nunit.org/articles/nunit/writing-tests/attributes/parallelizable.html"),
    api("retry", "[Retry(n)]", "Retry known transient failures.", "Use for infra flakes only.", "https://docs.nunit.org/articles/nunit/writing-tests/attributes/retry.html"),
  ],

  mocha: [
    api("describe-it", "describe / it", "Structure suites and cases.", "Classic BDD surface for JS.", "https://mochajs.org/#getting-started"),
    api("hooks", "before / after / beforeEach", "Lifecycle hooks.", "Isolate expensive setup.", "https://mochajs.org/#hooks"),
    api("async", "async it() / done()", "Async test completion.", "Promises are first-class.", "https://mochajs.org/#asynchronous-code"),
    api("retries", "this.retries(n)", "Retry flaky cases carefully.", "Prefer fixing root cause.", "https://mochajs.org/#retry-tests"),
    api("timeout", "this.timeout(ms)", "Per-suite timeouts.", "Slow integration needs headroom.", "https://mochajs.org/#timeouts"),
    api("exclusive", "describe.only / it.only", "Focus while debugging.", "Never leave .only in CI.", "https://mochajs.org/#exclusive-tests"),
    api("pending", "it.skip / xit", "Skip known broken cases.", "Track debt intentionally.", "https://mochajs.org/#pending-tests"),
    api("root-hooks", "mocha hooks files", "Global setup modules.", "Shared env bootstrap.", "https://mochajs.org/#root-hook-plugins"),
    api("reporters", "--reporter spec|xunit", "CI-friendly reporters.", "JUnit XML for gates.", "https://mochajs.org/#reporters"),
  ],

  robot: [
    api("testcase", "*** Test Cases ***", "Declare Robot cases.", "Keyword-driven structure.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-test-cases"),
    api("keywords", "*** Keywords ***", "Reusable keyword libraries.", "Compose business language.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-user-keywords"),
    api("variables", "${VAR} / @{LIST}", "Scalar and list variables.", "Parameterize suites.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variables"),
    api("setup-teardown", "[Setup] / [Teardown]", "Case and suite fixtures.", "Clean browser/API state.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#setups-and-teardowns"),
    api("tags", "[Tags] smoke", "Select and report by tag.", "PR filters via --include.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#tagging-test-cases"),
    api("for-if", "FOR / IF / TRY", "Control structures in RF.", "Express branching without Python.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#if-else-syntax"),
    api("libraries", "Library SeleniumLibrary", "Import keyword libraries.", "UI/API/DB via libraries.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#standard-libraries"),
    api("resource", "Resource path.resource", "Share keywords across suites.", "Avoid copy-paste suites.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#resource-and-variable-files"),
    api("listeners", "Listener interface", "Hook into execution.", "Custom metrics and evidence.", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface"),
  ],

  webdriverio: [
    api("url", "browser.url(path)", "Navigate with WebdriverIO.", "Entry for e2e specs.", "https://webdriver.io/docs/api/browser/url"),
    api("$", "$ / $$ selectors", "Query elements ($/$$).", "Chainable element APIs.", "https://webdriver.io/docs/api/browser/$"),
    api("waitUntil", "browser.waitUntil", "Custom wait conditions.", "Replace fixed pauses.", "https://webdriver.io/docs/api/browser/waitUntil"),
    api("setValue", "element.setValue / click", "Type and click helpers.", "Clear+type for inputs.", "https://webdriver.io/docs/api/element/setValue"),
    api("expect", "expect(el).toBeDisplayed()", "WDIO expect-webdriverio.", "Fluent assertions for elements.", "https://webdriver.io/docs/api/expect-webdriverio"),
    api("mock", "browser.mock(url)", "Mock network at CDP layer.", "Stub APIs in Chromium.", "https://webdriver.io/docs/api/browser/mock"),
    api("execute", "browser.execute(fn)", "Run script in the browser.", "Read client-only state.", "https://webdriver.io/docs/api/browser/execute"),
    api("switchWindow", "browser.switchWindow", "Handle multi-window flows.", "OAuth popups need switches.", "https://webdriver.io/docs/api/browser/switchWindow"),
    api("upload", "element.setValue(filePath)", "File uploads via local path.", "WDIO bridges file paths.", "https://webdriver.io/docs/api/element/addValue"),
    api("config", "wdio.conf.ts capabilities", "Projects, services, reporters.", "CI shape lives in config.", "https://webdriver.io/docs/configurationfile"),
  ],

  nightwatch: [
    api("url", "browser.url(url)", "Open a page in Nightwatch.", "Start of every journey.", "https://nightwatchjs.org/api/url/"),
    api("waitFor", "waitForElementVisible", "Explicit element waits.", "Built-in commands reduce flakes.", "https://nightwatchjs.org/api/waitForElementVisible/"),
    api("setValue", "setValue / click", "Interact with inputs.", "Command queue runs in order.", "https://nightwatchjs.org/api/setValue/"),
    api("assert", "assert.* / verify.*", "Hard vs soft assertions.", "verify continues after failure.", "https://nightwatchjs.org/api/assert/"),
    api("page-objects", "page objects API", "Encapsulate sections/commands.", "Scale Nightwatch suites.", "https://nightwatchjs.org/guide/using-page-objects/using-page-objects.html"),
    api("css-property", "assert.cssProperty", "Assert computed styles.", "Visual-ish checks without pixels.", "https://nightwatchjs.org/api/assert/#assert-cssProperty"),
    api("cookies", "browser.getCookie", "Manage cookies in session.", "Seed auth state.", "https://nightwatchjs.org/api/getCookie/"),
    api("screenshot", "browser.saveScreenshot", "Capture PNGs on failure.", "CI artifacts for triage.", "https://nightwatchjs.org/api/saveScreenshot/"),
    api("chrome-devtools", "Chrome DevTools commands", "Network and performance hooks.", "Modern Chromium power.", "https://nightwatchjs.org/guide/running-tests/using-chrome-devtools.html"),
  ],

  isafe: [
    api("workbook", "Excel/CSV data workbooks", "Drive cases from spreadsheets.", "Business users edit data rows.", "https://example.com/isafe"),
    api("keywords", "Keyword columns", "Map columns to actions.", "Data-driven without raw scripts.", "https://example.com/isafe"),
    api("modules", "Reusable modules", "Share flows across workbooks.", "DRY enterprise suites.", "https://example.com/isafe"),
    api("env-sheets", "Environment sheets", "Swap endpoints per env.", "Same cases, different stacks.", "https://example.com/isafe"),
    api("assertions", "Expected columns", "Assert outcomes from data.", "Expected results travel with inputs.", "https://example.com/isafe"),
    api("reporting", "Run reports", "Publish pass/fail by row.", "Row-level evidence for audits.", "https://example.com/isafe"),
    api("ci", "Headless CI runners", "Execute workbooks in pipeline.", "Gate builds on data suites.", "https://example.com/isafe"),
    api("hybrid", "UI + API rows", "Mix layers in one workbook.", "End-to-end business paths.", "https://example.com/isafe"),
  ],

  bdd: [
    api("ubiquitous", "Ubiquitous language", "Shared vocabulary across roles.", "BDD fails without shared words.", "https://cucumber.io/docs/bdd/"),
    api("example-mapping", "Example mapping", "Discover rules before automation.", "Cheap design workshops.", "https://cucumber.io/docs/bdd/example-mapping/"),
    api("given-when-then", "Given / When / Then", "Structure scenarios by intent.", "Keep When singular when possible.", "https://cucumber.io/docs/gherkin/reference/"),
    api("living-docs", "Living documentation", "Features as product docs.", "Specs stay honest via CI.", "https://cucumber.io/docs/bdd/"),
    api("anti-ui", "Avoid UI in every step", "Push detail to lower layers.", "Fast feedback, less flake.", "https://cucumber.io/docs/guides/anti-patterns/"),
    api("three-amigos", "Three Amigos sessions", "PO + dev + QA align examples.", "Prevent misunderstood stories.", "https://cucumber.io/docs/bdd/"),
    api("automation-pyramid", "BDD + test pyramid", "Few UI scenarios, many API/unit.", "Healthy suite shape.", "https://martinfowler.com/articles/practical-test-pyramid.html"),
    api("metrics", "Scenario pass rates / WIP tags", "Track automation health.", "@wip should shrink over time.", "https://cucumber.io/docs/cucumber/api/#tags"),
  ],

  "api-testing": [
    api("get", "GET /resource", "Read resources over HTTP.", "Safe idempotent reads.", "https://restful-api.dev/"),
    api("post", "POST /resource", "Create resources.", "Assert 201 + Location/body.", "https://restful-api.dev/"),
    api("put-patch", "PUT / PATCH", "Replace or partial update.", "Idempotency differs by verb.", "https://restful-api.dev/"),
    api("delete", "DELETE /resource/{id}", "Remove resources.", "Assert 204/404 semantics.", "https://restful-api.dev/"),
    api("auth", "Bearer / Basic / API keys", "Authenticate requests.", "Negative auth is mandatory.", "https://swagger.io/docs/specification/authentication/"),
    api("schema", "JSON Schema / OpenAPI assert", "Validate response shapes.", "Contracts catch silent breaks.", "https://json-schema.org/"),
    api("status", "assert status codes", "Check HTTP status families.", "200 vs 201 vs 204 matter.", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"),
    api("headers", "Assert content-type / cache", "Header contracts.", "CORS and caching bugs hide here.", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers"),
    api("pagination", "page/cursor params", "Traverse collections.", "Off-by-one and empty pages.", "https://restfulapi.net/pagination/"),
    api("idempotency", "Idempotency-Key", "Safe retries for POSTs.", "Payments need idempotent writes.", "https://stripe.com/docs/api/idempotent_requests"),
    api("negative", "4xx / 5xx cases", "Invalid payloads and auth.", "Negative suite is half the value.", "https://restful-api.dev/"),
    api("contract", "Consumer-driven contracts", "Pact-style consumer checks.", "Microservices need CDC.", "https://docs.pact.io/"),
  ],

  jmeter: [
    api("thread-group", "Thread Group", "Virtual users and ramp-up.", "Load shape starts here.", "https://jmeter.apache.org/usermanual/test_plan.html#thread_group"),
    api("http-sampler", "HTTP Request sampler", "Fire HTTP under load.", "Core of API/web load tests.", "https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Request"),
    api("listeners", "Listeners / reports", "Observe results carefully.", "Prefer backend listeners in CI.", "https://jmeter.apache.org/usermanual/component_reference.html#listeners"),
    api("assertions", "Response Assertion", "Pass/fail under load.", "Load without asserts is noise.", "https://jmeter.apache.org/usermanual/component_reference.html#Response_Assertion"),
    api("csv-config", "CSV Data Set Config", "Parameterize users/data.", "Unique data per virtual user.", "https://jmeter.apache.org/usermanual/component_reference.html#CSV_Data_Set_Config"),
    api("timers", "Timers / think time", "Model real user pacing.", "Avoid unrealistic stampedes.", "https://jmeter.apache.org/usermanual/component_reference.html#timers"),
    api("controllers", "Logic controllers", "If/foreach/transaction controllers.", "Structure complex journeys.", "https://jmeter.apache.org/usermanual/component_reference.html#logic_controllers"),
    api("cli", "jmeter -n -t plan.jmx", "Non-GUI CI execution.", "Always run headless in pipelines.", "https://jmeter.apache.org/usermanual/get-started.html#non_gui"),
    api("distributed", "Remote engines", "Scale generators horizontally.", "One box saturates quickly.", "https://jmeter.apache.org/usermanual/remote-test.html"),
  ],

  k6: [
    api("http-get", "http.get(url)", "HTTP GET in k6 scripts.", "Core request helper.", "https://grafana.com/docs/k6/latest/javascript-api/k6-http/get/"),
    api("http-post", "http.post(url, body)", "POST JSON under load.", "Create-heavy scenarios.", "https://grafana.com/docs/k6/latest/javascript-api/k6-http/post/"),
    api("check", "check(res, {...})", "Threshold-friendly checks.", "Checks ≠ thresholds — know both.", "https://grafana.com/docs/k6/latest/javascript-api/k6/check/"),
    api("thresholds", "thresholds: { http_req_failed }", "Fail the run on SLOs.", "CI gates on error rate/latency.", "https://grafana.com/docs/k6/latest/using-k6/thresholds/"),
    api("stages", "stages / scenarios", "Ramp VUs over time.", "Model soak and spike tests.", "https://grafana.com/docs/k6/latest/using-k6/scenarios/"),
    api("sleep", "sleep(seconds)", "Think time between iterations.", "Human pacing.", "https://grafana.com/docs/k6/latest/javascript-api/k6/sleep/"),
    api("group", "group(name, fn)", "Name journey segments.", "Readable metrics per step.", "https://grafana.com/docs/k6/latest/javascript-api/k6/group/"),
    api("trend", "new Trend('name')", "Custom metrics.", "Business KPIs under load.", "https://grafana.com/docs/k6/latest/javascript-api/k6-metrics/"),
    api("executors", "constant-vus / ramping-arrival", "Choose arrival models.", "Match production traffic shape.", "https://grafana.com/docs/k6/latest/using-k6/scenarios/executors/"),
    api("cloud", "k6 cloud / output", "Stream results to Grafana Cloud.", "Share load reports with teams.", "https://grafana.com/docs/k6/latest/results-output/real-time/cloud/"),
  ],

  artillery: [
    api("scenarios", "scenarios: - flow:", "Declare user flows in YAML.", "Readable load definitions.", "https://www.artillery.io/docs/reference/test-script"),
    api("get-post", "get: / post:", "HTTP steps in a flow.", "Chain API calls under load.", "https://www.artillery.io/docs/reference/engines/http"),
    api("capture", "capture: json", "Extract values for next steps.", "Correlation like JMeter extractors.", "https://www.artillery.io/docs/reference/engines/http#extracting-data"),
    api("expect", "expect: statusCode", "Assert responses in flow.", "Functional checks under load.", "https://www.artillery.io/docs/reference/engines/http#expect-plugin"),
    api("phases", "phases: arrivalRate", "Warm-up and sustained load.", "Control arrival patterns.", "https://www.artillery.io/docs/reference/test-script#phases"),
    api("payload", "payload: path.csv", "CSV-driven virtual users.", "Unique identities per VU.", "https://www.artillery.io/docs/reference/test-script#payload"),
    api("processor", "processor.js functions", "JS hooks for custom logic.", "Sign requests or compute IDs.", "https://www.artillery.io/docs/reference/test-script#processor"),
    api("plugins", "plugins: expect / publish-metrics", "Extend Artillery runs.", "Ship metrics to backends.", "https://www.artillery.io/docs/reference/extensions"),
    api("cli", "artillery run script.yml", "Execute in CI.", "Exit codes gate pipelines.", "https://www.artillery.io/docs/get-started/first-test"),
  ],

  sql: [
    api("select", "SELECT ... FROM ... WHERE", "Query rows with filters.", "Core read path for QA checks.", "https://www.postgresql.org/docs/current/sql-select.html"),
    api("join", "INNER/LEFT JOIN", "Relate tables in one query.", "Hybrid UI+DB asserts need joins.", "https://www.postgresql.org/docs/current/tutorial-join.html"),
    api("aggregate", "COUNT / SUM / GROUP BY", "Aggregate for invariants.", "Totals must match UI carts.", "https://www.postgresql.org/docs/current/tutorial-agg.html"),
    api("insert", "INSERT INTO ... VALUES", "Seed fixtures via SQL.", "Faster than UI for setup.", "https://www.postgresql.org/docs/current/sql-insert.html"),
    api("update", "UPDATE ... SET", "Mutate rows for scenarios.", "Force edge-case states.", "https://www.postgresql.org/docs/current/sql-update.html"),
    api("delete", "DELETE FROM ...", "Cleanup or soft-delete checks.", "Teardown hermetic data.", "https://www.postgresql.org/docs/current/sql-delete.html"),
    api("transactions", "BEGIN / COMMIT / ROLLBACK", "Isolate test mutations.", "Never leave dirty committed data.", "https://www.postgresql.org/docs/current/tutorial-transactions.html"),
    api("indexes", "EXPLAIN / indexes", "Read query plans.", "Perf bugs show in EXPLAIN.", "https://www.postgresql.org/docs/current/using-explain.html"),
    api("constraints", "PK / FK / UNIQUE / CHECK", "Assert integrity rules.", "DB enforces what UI forgets.", "https://www.postgresql.org/docs/current/ddl-constraints.html"),
    api("nulls", "IS NULL / COALESCE", "Handle missing data.", "NULL semantics break naive asserts.", "https://www.postgresql.org/docs/current/functions-comparison.html"),
  ],

  postgresql: [
    api("psycopg", "psycopg / asyncpg clients", "Connect from Python tests.", "Preferred drivers for pytest.", "https://www.psycopg.org/psycopg3/docs/"),
    api("select", "SELECT with parameters", "Parameterized queries only.", "Never string-format SQL.", "https://www.psycopg.org/psycopg3/docs/basic/params.html"),
    api("jsonb", "JSONB operators", "Query JSON documents.", "Modern schemas store JSONB.", "https://www.postgresql.org/docs/current/datatype-json.html"),
    api("cte", "WITH cte AS (...)", "Readable multi-step SQL.", "Complex hybrid asserts.", "https://www.postgresql.org/docs/current/queries-with.html"),
    api("upsert", "INSERT ... ON CONFLICT", "Idempotent seeds.", "Re-runnable fixtures.", "https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT"),
    api("listen-notify", "LISTEN / NOTIFY", "Eventing between sessions.", "Rare but powerful for e2e.", "https://www.postgresql.org/docs/current/sql-notify.html"),
    api("migrations", "schema migrations", "Version DB in CI.", "Tests need migrate-up jobs.", "https://www.postgresql.org/docs/current/ddl.html"),
    api("roles", "GRANT / RLS basics", "Permission testing.", "AuthZ bugs live in DB too.", "https://www.postgresql.org/docs/current/ddl-rowsecurity.html"),
    api("copy", "COPY / \\copy", "Bulk load fixtures.", "Fast seed for large sets.", "https://www.postgresql.org/docs/current/sql-copy.html"),
  ],

  snowflake: [
    api("warehouse", "USE WAREHOUSE", "Select compute warehouse.", "Cost and concurrency knobs.", "https://docs.snowflake.com/en/sql-reference/sql/use-warehouse"),
    api("select", "SELECT from cloud tables", "Query analytical tables.", "QA validates transforms.", "https://docs.snowflake.com/en/sql-reference/sql/select"),
    api("stages", "CREATE STAGE / COPY INTO", "Load files from stages.", "Pipeline freshness checks.", "https://docs.snowflake.com/en/sql-reference/sql/copy-into-table"),
    api("tasks", "CREATE TASK", "Schedule SQL pipelines.", "Assert task success history.", "https://docs.snowflake.com/en/sql-reference/sql/create-task"),
    api("time-travel", "AT (TIMESTAMP => ...)", "Query historical data.", "Debug bad loads safely.", "https://docs.snowflake.com/en/user-guide/data-time-travel"),
    api("clones", "CREATE ... CLONE", "Zero-copy env clones.", "Isolated QA databases.", "https://docs.snowflake.com/en/sql-reference/sql/create-clone"),
    api("rbac", "roles & grants", "Least-privilege access.", "Security tests for warehouses.", "https://docs.snowflake.com/en/user-guide/security-access-control"),
    api("snowpark", "Snowpark DataFrames", "Programmatic transforms.", "Test Python/Java pipelines.", "https://docs.snowflake.com/en/developer-guide/snowpark/index"),
    api("quality", "data quality metrics", "Null rates, dupes, freshness.", "Analytics QA checklist.", "https://docs.snowflake.com/en/user-guide/data-quality-and-observability"),
  ],

  "azure-devops": [
    api("pipeline-yaml", "azure-pipelines.yml", "Declare CI stages/jobs.", "PR gates live here.", "https://learn.microsoft.com/azure/devops/pipelines/yaml-schema"),
    api("stages", "stages: - stage:", "Sequence build/test/deploy.", "Separate concerns cleanly.", "https://learn.microsoft.com/azure/devops/pipelines/process/stages"),
    api("jobs-steps", "jobs / steps / tasks", "Compose pipeline work.", "Reuse task marketplace pieces.", "https://learn.microsoft.com/azure/devops/pipelines/process/phases"),
    api("variables", "variables / variable groups", "Config and secrets refs.", "Keep secrets out of YAML.", "https://learn.microsoft.com/azure/devops/pipelines/process/variables"),
    api("artifacts", "PublishPipelineArtifact", "Persist test reports.", "JUnit/Allure for gates.", "https://learn.microsoft.com/azure/devops/pipelines/artifacts/pipeline-artifacts"),
    api("environments", "environments + approvals", "Deploy with checks.", "Human gates for prod.", "https://learn.microsoft.com/azure/devops/pipelines/process/environments"),
    api("templates", "extends / template", "Share pipeline fragments.", "Org standards as code.", "https://learn.microsoft.com/azure/devops/pipelines/process/templates"),
    api("test-results", "PublishTestResults", "Surface pytest/jUnit.", "Failures block PRs.", "https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/publish-test-results-v2"),
    api("boards", "work items API", "Trace bugs to commits.", "DevOps feedback loop.", "https://learn.microsoft.com/azure/devops/boards/"),
  ],

  jenkins: [
    api("pipeline", "pipeline { ... }", "Declarative Jenkinsfile.", "CI as code.", "https://www.jenkins.io/doc/book/pipeline/syntax/"),
    api("stages", "stage('Test')", "Named pipeline stages.", "Visualize progress.", "https://www.jenkins.io/doc/book/pipeline/syntax/#stage"),
    api("agent", "agent { label ... }", "Pick executors.", "Browser vs API agents.", "https://www.jenkins.io/doc/book/pipeline/syntax/#agent"),
    api("parallel", "parallel { ... }", "Fan-out test shards.", "Cut wall clock.", "https://www.jenkins.io/doc/book/pipeline/syntax/#parallel"),
    api("post", "post { always { } }", "Archive & notify always.", "Artifacts on failure too.", "https://www.jenkins.io/doc/book/pipeline/syntax/#post"),
    api("credentials", "withCredentials", "Inject secrets safely.", "Never echo tokens.", "https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials"),
    api("junit", "junit 'reports/*.xml'", "Publish JUnit results.", "Trend flakes over time.", "https://www.jenkins.io/doc/pipeline/steps/junit/"),
    api("shared-lib", "shared libraries", "@Library('ci') _", "Org-wide steps.", "https://www.jenkins.io/doc/book/pipeline/shared-libraries/"),
    api("triggers", "cron / pollSCM / webhook", "When pipelines run.", "PR vs nightly schedules.", "https://www.jenkins.io/doc/book/pipeline/syntax/#triggers"),
  ],

  docker: [
    api("build", "docker build -t image .", "Build images reproducibly.", "Tests need frozen images.", "https://docs.docker.com/reference/cli/docker/image/build/"),
    api("run", "docker run ...", "Start containers with ports/env.", "Ephemeral deps for CI.", "https://docs.docker.com/reference/cli/docker/container/run/"),
    api("compose", "docker compose up", "Multi-service stacks.", "App+DB+wiremock together.", "https://docs.docker.com/compose/"),
    api("exec", "docker exec -it", "Shell into running containers.", "Debug failing CI services.", "https://docs.docker.com/reference/cli/docker/container/exec/"),
    api("logs", "docker logs / compose logs", "Capture service output.", "First place for 5xx root cause.", "https://docs.docker.com/reference/cli/docker/container/logs/"),
    api("volumes", "volumes: ...", "Persist or mount test data.", "Fixtures and reports.", "https://docs.docker.com/storage/volumes/"),
    api("networks", "networks / aliases", "Service discovery in compose.", "DNS names between containers.", "https://docs.docker.com/network/"),
    api("healthcheck", "HEALTHCHECK", "Ready gates before tests.", "Avoid racey suite starts.", "https://docs.docker.com/reference/dockerfile/#healthcheck"),
    api("multistage", "FROM ... AS build", "Slim runtime images.", "Smaller attack surface.", "https://docs.docker.com/build/building/multi-stage/"),
  ],

  aws: [
    api("cli", "aws <service> <op>", "CLI for cloud resources.", "Scriptable verification.", "https://docs.aws.amazon.com/cli/latest/userguide/"),
    api("s3", "s3 cp / ls / rm", "Object storage checks.", "Artifact and data pipelines.", "https://docs.aws.amazon.com/cli/latest/reference/s3/"),
    api("lambda", "lambda invoke", "Invoke functions under test.", "Assert payloads and errors.", "https://docs.aws.amazon.com/lambda/latest/dg/testing-functions.html"),
    api("dynamodb", "dynamodb get/put/query", "NoSQL state asserts.", "Hybrid API+DB style.", "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/"),
    api("sqs", "sqs send/receive", "Queue-based flows.", "Async systems need waits.", "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/"),
    api("cloudwatch", "logs filter / metrics", "Observe failures.", "QA reads ops signals.", "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/"),
    api("iam", "iam simulate / policies", "Permission boundary tests.", "AuthZ bugs are defects.", "https://docs.aws.amazon.com/IAM/latest/UserGuide/"),
    api("cdk-cfn", "stacks / outputs", "Infra as code outputs.", "Wire tests to stack outputs.", "https://docs.aws.amazon.com/cdk/v2/guide/home.html"),
    api("sts", "sts assume-role", "Temporary credentials.", "Least privilege for CI.", "https://docs.aws.amazon.com/STS/latest/APIReference/"),
  ],

  azure: [
    api("az-cli", "az <group> <cmd>", "Azure CLI automation.", "Script resource checks.", "https://learn.microsoft.com/cli/azure/"),
    api("appservice", "az webapp ...", "Deploy/verify web apps.", "Slot swaps and health.", "https://learn.microsoft.com/cli/azure/webapp"),
    api("functions", "az functionapp", "Serverless function ops.", "Invoke and watch logs.", "https://learn.microsoft.com/azure/azure-functions/"),
    api("storage", "az storage blob", "Blob/file asserts.", "Upload evidence and fixtures.", "https://learn.microsoft.com/cli/azure/storage/blob"),
    api("keyvault", "az keyvault secret", "Secrets for test config.", "Never commit secrets.", "https://learn.microsoft.com/cli/azure/keyvault/secret"),
    api("monitor", "az monitor metrics", "Platform metrics/logs.", "SLO evidence in QA.", "https://learn.microsoft.com/cli/azure/monitor"),
    api("aad", "service principals", "App auth for CI.", "Federated credentials preferred.", "https://learn.microsoft.com/entra/identity-platform/"),
    api("bicep", "az deployment ...", "Infra templates.", "Env parity via IaC.", "https://learn.microsoft.com/azure/azure-resource-manager/bicep/"),
    api("aks", "az aks / kubectl", "Kubernetes workloads.", "Probe pods and services.", "https://learn.microsoft.com/azure/aks/"),
  ],

  git: [
    api("clone-fetch", "git clone / fetch", "Get remote history.", "CI starts with a clean fetch.", "https://git-scm.com/docs/git-clone"),
    api("branch", "git switch -c", "Create topic branches.", "Isolate work per change.", "https://git-scm.com/docs/git-switch"),
    api("commit", "git commit", "Record snapshots.", "Atomic commits aid bisect.", "https://git-scm.com/docs/git-commit"),
    api("rebase-merge", "rebase / merge", "Integrate history.", "Know when to rebase vs merge.", "https://git-scm.com/docs/git-rebase"),
    api("stash", "git stash", "Park local changes.", "Context switch safely.", "https://git-scm.com/docs/git-stash"),
    api("diff-log", "git diff / log", "Inspect changes.", "Review before push.", "https://git-scm.com/docs/git-diff"),
    api("tag", "git tag", "Mark releases.", "Trace builds to tags.", "https://git-scm.com/docs/git-tag"),
    api("hooks", "pre-commit hooks", "Local quality gates.", "Lint before CI.", "https://git-scm.com/docs/githooks"),
    api("bisect", "git bisect", "Find regressing commits.", "Power tool for flakes.", "https://git-scm.com/docs/git-bisect"),
  ],

  bitbucket: [
    api("pipelines", "bitbucket-pipelines.yml", "Define Bitbucket Pipelines.", "PR checks as code.", "https://support.atlassian.com/bitbucket-cloud/docs/bitbucket-pipelines-configuration-reference/"),
    api("steps", "step: script:", "Commands per step.", "Cache and artifacts options.", "https://support.atlassian.com/bitbucket-cloud/docs/configure-your-pipeline/"),
    api("parallel", "parallel: steps", "Fan-out jobs.", "Shard browsers/tests.", "https://support.atlassian.com/bitbucket-cloud/docs/parallel-steps/"),
    api("deployments", "deployment: production", "Environment promote.", "Track deploy history.", "https://support.atlassian.com/bitbucket-cloud/docs/variables-in-pipelines/"),
    api("vars", "repository variables", "Secrets and config.", "Secured variables for tokens.", "https://support.atlassian.com/bitbucket-cloud/docs/variables-in-pipelines/"),
    api("artifacts", "artifacts: - reports/**", "Pass files between steps.", "JUnit to reporting step.", "https://support.atlassian.com/bitbucket-cloud/docs/step-options/"),
    api("pr-checks", "pull request triggers", "Run on PR open/sync.", "Block merges on red.", "https://support.atlassian.com/bitbucket-cloud/docs/pipeline-triggers/"),
    api("code-insights", "Code Insights reports", "Annotate PRs with results.", "Surfaces test failures in UI.", "https://developer.atlassian.com/cloud/bitbucket/rest/intro/#code-insights"),
    api("branching", "branch permissions", "Protect main.", "Require green builds.", "https://support.atlassian.com/bitbucket-cloud/docs/use-branch-permissions/"),
  ],

  "service-cloud": [
    api("cases", "Case object CRUD", "Create/update support cases.", "Core Service Cloud entity.", "https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_case.htm"),
    api("soql", "SOQL queries", "Query Salesforce data.", "Assert case fields after UI.", "https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/"),
    api("rest", "SObject REST API", "HTTP automation for CRM.", "Faster than full UI.", "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/"),
    api("apex-tests", "@isTest classes", "Apex unit tests.", "Required coverage for deploys.", "https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing.htm"),
    api("omni-channel", "Omni-Channel routing", "Work distribution rules.", "Assert agent routing.", "https://help.salesforce.com/s/articleView?id=sf.service_presence_intro.htm"),
    api("entitlements", "Entitlements / milestones", "SLA timers on cases.", "Time-based QA scenarios.", "https://help.salesforce.com/s/articleView?id=sf.entitlements_overview.htm"),
    api("knowledge", "Knowledge articles", "Attach knowledge to cases.", "Deflection and agent assist.", "https://help.salesforce.com/s/articleView?id=sf.knowledge_whatis.htm"),
    api("lightning", "Lightning UI automation", "UI tests for consoles.", "Use accessible locators.", "https://developer.salesforce.com/docs/platform/lightning-component-reference"),
    api("scratch-orgs", "scratch orgs / sandboxes", "Ephemeral test orgs.", "Isolate automation data.", "https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs.htm"),
  ],

  "experience-cloud": [
    api("sites", "Experience Cloud sites", "Configure digital experiences.", "Portal UX under test.", "https://help.salesforce.com/s/articleView?id=sf.networks_overview.htm"),
    api("audiences", "Audience targeting", "Personalize by audience.", "Assert variant content.", "https://help.salesforce.com/s/articleView?id=sf.community_builder_audiences.htm"),
    api("lwr", "LWR / Aura pages", "Page runtime models.", "Know which stack you automate.", "https://developer.salesforce.com/docs/platform/lwc/guide"),
    api("auth", "Experience auth / SSO", "Login as community user.", "Auth is the hardest path.", "https://help.salesforce.com/s/articleView?id=sf.networks_authentication.htm"),
    api("cms", "CMS content", "Managed content on sites.", "Content changes break locators.", "https://help.salesforce.com/s/articleView?id=sf.cms_overview.htm"),
    api("navigation", "Navigation menus", "Information architecture.", "Deep links in tests.", "https://help.salesforce.com/s/articleView?id=sf.community_builder_navigation.htm"),
    api("accessibility", "A11y on portals", "Role/name locators.", "Public sites need a11y.", "https://www.w3.org/WAI/WCAG21/quickref/"),
    api("perf", "Page performance", "LCP/CLS for portals.", "Marketing pages regress easily.", "https://web.dev/articles/vitals"),
    api("automation", "UI + API hybrid", "API seed + UI assert.", "Fast reliable portal tests.", "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/"),
  ],

  flows: [
    api("record-triggered", "Record-triggered flows", "Automate on create/update.", "Most common Flow type.", "https://help.salesforce.com/s/articleView?id=sf.flow_concepts_trigger.htm"),
    api("screen-flow", "Screen flows", "Guided UI for users.", "UI automation for screens.", "https://help.salesforce.com/s/articleView?id=sf.flow_concepts_screen.htm"),
    api("autolaunched", "Autolaunched / scheduled", "Headless automation.", "Test via API side effects.", "https://help.salesforce.com/s/articleView?id=sf.flow_concepts_trigger_schedule.htm"),
    api("decision", "Decision elements", "Branching logic.", "Cover each outcome path.", "https://help.salesforce.com/s/articleView?id=sf.flow_ref_elements_decision.htm"),
    api("loop", "Loop elements", "Iterate collections.", "Bulk paths need volume data.", "https://help.salesforce.com/s/articleView?id=sf.flow_ref_elements_loop.htm"),
    api("fault", "Fault paths", "Error handling routes.", "Negative tests hit faults.", "https://help.salesforce.com/s/articleView?id=sf.flow_concepts_fault_path.htm"),
    api("subflow", "Subflows", "Compose reusable flows.", "Unit-test building blocks.", "https://help.salesforce.com/s/articleView?id=sf.flow_concepts_subflow.htm"),
    api("debug", "Flow debug / interviews", "Step through interviews.", "Reproduce prod failures.", "https://help.salesforce.com/s/articleView?id=sf.flow_debug.htm"),
    api("tests", "Flow tests (Spring features)", "Declarative Flow tests.", "Regression without Apex only.", "https://help.salesforce.com/s/articleView?id=sf.flow_test.htm"),
  ],

  deepeval: [
    api("llm-test-case", "LLMTestCase(...)", "Package input/output/context.", "Unit of LLM evaluation.", "https://deepeval.com/docs/evaluation-test-cases"),
    api("assert-test", "assert_test(case, metrics)", "Run metrics as pytest.", "CI-native LLM gates.", "https://deepeval.com/docs/evaluation-introduction"),
    api("faithfulness", "FaithfulnessMetric", "Groundedness vs retrieval.", "Catch hallucinations.", "https://deepeval.com/docs/metrics-faithfulness"),
    api("answer-relevancy", "AnswerRelevancyMetric", "Answer vs user question.", "Off-topic responses fail.", "https://deepeval.com/docs/metrics-answer-relevancy"),
    api("contextual-precision", "ContextualPrecisionMetric", "Ranking quality of context.", "RAG retrieval quality.", "https://deepeval.com/docs/metrics-contextual-precision"),
    api("geval", "GEval", "Custom criteria via judge LLM.", "Domain-specific rubrics.", "https://deepeval.com/docs/metrics-llm-evals"),
    api("conversation", "ConversationalTestCase", "Multi-turn evaluation.", "Agents need turn metrics.", "https://deepeval.com/docs/evaluation-multiturn"),
    api("redteam", "red-teaming scans", "Adversarial prompts.", "Safety regression suite.", "https://deepeval.com/docs/red-teaming-introduction"),
    api("dataset", "EvaluationDataset / Golden", "Batch goldens.", "Curate living eval sets.", "https://deepeval.com/docs/evaluation-datasets"),
    api("custom-metric", "BaseMetric subclass", "Org-specific metrics.", "Encode business rules.", "https://deepeval.com/docs/metrics-custom"),
  ],

  ragas: [
    api("evaluate", "evaluate(dataset, metrics)", "Run RAGAS metrics batch.", "Standard RAG scorecard.", "https://docs.ragas.io/en/latest/concepts/evaluation/"),
    api("faithfulness", "faithfulness", "Groundedness metric.", "Hallucination detector.", "https://docs.ragas.io/en/latest/concepts/metrics/available_metrics/faithfulness/"),
    api("answer-relevancy", "answer_relevancy", "Relevance to question.", "Core quality signal.", "https://docs.ragas.io/en/latest/concepts/metrics/available_metrics/answer_relevance/"),
    api("context-precision", "context_precision", "Retrieved context precision.", "Ranking quality.", "https://docs.ragas.io/en/latest/concepts/metrics/available_metrics/context_precision/"),
    api("context-recall", "context_recall", "Did we retrieve enough?", "Coverage of needed facts.", "https://docs.ragas.io/en/latest/concepts/metrics/available_metrics/context_recall/"),
    api("dataset", "Dataset.from_list", "Build eval datasets.", "Traceable goldens.", "https://docs.ragas.io/en/latest/getstarted/rag_eval/"),
    api("llm-setup", "llm / embeddings config", "Configure judge models.", "Determinism vs cost tradeoffs.", "https://docs.ragas.io/en/latest/getstarted/install/"),
    api("custom", "custom metrics", "Extend metric set.", "Domain rubrics.", "https://docs.ragas.io/en/latest/howtos/customizations/"),
    api("ci", "pytest + ragas scores", "Gate PRs on thresholds.", "Fail builds on quality drops.", "https://docs.ragas.io/en/latest/howtos/integrations/_pytest/"),
  ],

  langsmith: [
    api("trace", "traceable / @traceable", "Trace LLM runs.", "Debug prompts & tools.", "https://docs.langchain.com/langsmith/"),
    api("datasets", "LangSmith datasets", "Curate examples.", "Human feedback loops.", "https://docs.langchain.com/langsmith/evaluation"),
    api("evaluate", "evaluate(target, data)", "Run evaluators on datasets.", "Offline eval harness.", "https://docs.langchain.com/langsmith/evaluation"),
    api("feedback", "create_feedback", "Attach scores to runs.", "Label production traces.", "https://docs.langchain.com/langsmith/"),
    api("playground", "Prompt playground", "Iterate prompts visually.", "Share with PMs.", "https://docs.langchain.com/langsmith/"),
    api("comparisons", "compare experiments", "A/B prompt versions.", "Pick winners with data.", "https://docs.langchain.com/langsmith/evaluation"),
    api("filters", "trace filters / threads", "Find failing conversations.", "Production incident triage.", "https://docs.langchain.com/langsmith/"),
    api("sdk", "Client() Python/JS", "Automate LangSmith ops.", "CI uploads experiments.", "https://docs.langchain.com/langsmith/"),
    api("online", "online evaluators", "Score live traffic.", "Continuous quality.", "https://docs.langchain.com/langsmith/"),
  ],

  rag: [
    api("chunking", "chunk / split documents", "Segment corpus for retrieval.", "Chunk size changes answers.", "https://python.langchain.com/docs/modules/data_connection/document_transformers/"),
    api("embed", "embed_documents / embed_query", "Vectorize text.", "Embedding model is a dependency.", "https://python.langchain.com/docs/modules/data_connection/text_embedding/"),
    api("index", "vector store upsert", "Persist embeddings.", "Index freshness matters.", "https://python.langchain.com/docs/modules/data_connection/vectorstores/"),
    api("retrieve", "similarity_search(k)", "Fetch top-k contexts.", "k and filters change quality.", "https://python.langchain.com/docs/modules/data_connection/retrievers/"),
    api("rerank", "cross-encoder rerank", "Reorder retrieved chunks.", "Precision@k improvements.", "https://python.langchain.com/docs/modules/data_connection/retrievers/"),
    api("generate", "LLM generate with context", "Answer from retrieved docs.", "Prompt must cite context.", "https://python.langchain.com/docs/modules/chains/"),
    api("citations", "require citations", "Ground answers in sources.", "User trust + eval signal.", "https://www.anthropic.com/research"),
    api("eval-set", "question / context / answer goldens", "Golden RAG triples.", "Regression pack for RAG.", "https://docs.ragas.io/en/latest/getstarted/rag_eval/"),
    api("failure-modes", "miss / hallucination / refusal", "Taxonomy of RAG bugs.", "Test each failure mode.", "https://docs.ragas.io/en/latest/concepts/metrics/"),
  ],

  "agentic-ai": [
    api("tool-calls", "tool / function calling", "Assert tools invoked correctly.", "Wrong tool = failed task.", "https://langchain-ai.github.io/langgraph/"),
    api("graph", "StateGraph / nodes / edges", "Agent control flow.", "Test node contracts.", "https://langchain-ai.github.io/langgraph/concepts/low_level/"),
    api("state", "agent state schema", "Typed state between nodes.", "Invalid state is a bug.", "https://langchain-ai.github.io/langgraph/concepts/low_level/"),
    api("memory", "checkpointers / memory", "Multi-turn continuity.", "Memory leaks private data.", "https://langchain-ai.github.io/langgraph/concepts/persistence/"),
    api("timeouts", "step / overall budgets", "Bound agent runtime.", "Infinite loops are defects.", "https://langchain-ai.github.io/langgraph/"),
    api("handoffs", "human-in-the-loop", "Escalation paths.", "Test interrupt + resume.", "https://langchain-ai.github.io/langgraph/concepts/human_in_the_loop/"),
    api("evals", "trajectory evaluations", "Score tool sequences.", "Process and outcome metrics.", "https://deepeval.com/docs/metrics-agent"),
    api("safety", "policy / allow-lists", "Block dangerous tools.", "Security tests for agents.", "https://owasp.org/www-project-top-10-for-large-language-model-applications/"),
    api("observability", "traces for agents", "Inspect each step.", "Debug without guessing.", "https://docs.langchain.com/langsmith/"),
  ],

  "github-copilot": [
    api("inline", "inline completions", "Suggest code in editor.", "Review before accept.", "https://docs.github.com/en/copilot"),
    api("chat", "Copilot Chat", "Ask for tests/refactors.", "Prompt with constraints.", "https://docs.github.com/en/copilot/using-github-copilot/asking-github-copilot-questions-in-your-ide"),
    api("tests", "generate unit tests", "Draft test scaffolding.", "You still own assertions.", "https://docs.github.com/en/copilot"),
    api("pr", "Copilot on pull requests", "Summaries and reviews.", "Human merge authority.", "https://docs.github.com/en/copilot"),
    api("cli", "gh copilot", "CLI assistance.", "Terminal workflows.", "https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-in-the-cli"),
    api("prompts", "prompt patterns for QA", "Given/When/Then prompts.", "Better prompts → better tests.", "https://docs.github.com/en/copilot/using-github-copilot/best-practices"),
    api("security", "secret scanning awareness", "Never paste secrets.", "Treat chat as external.", "https://docs.github.com/en/code-security"),
    api("policy", "org policies / enablement", "Govern Copilot rollout.", "Compliance for enterprises.", "https://docs.github.com/en/copilot/managing-copilot"),
    api("eval", "accept/edit/reject metrics", "Measure assistant value.", "Track rework rate.", "https://docs.github.com/en/copilot"),
  ],

  "ms-copilot": [
    api("m365-chat", "Microsoft 365 Copilot chat", "Grounded enterprise chat.", "Permissions bound answers.", "https://learn.microsoft.com/microsoft-365-copilot/"),
    api("plugins", "plugins / extensions", "Extend Copilot actions.", "Test tool permissions.", "https://learn.microsoft.com/microsoft-365-copilot/extensibility/"),
    api("graph", "Microsoft Graph grounding", "Data from Graph.", "Assert correct scopes.", "https://learn.microsoft.com/graph/"),
    api("prompts", "prompt & grounding hygiene", "Clear task + sources.", "Reduce hallucination risk.", "https://learn.microsoft.com/microsoft-365-copilot/"),
    api("security", "DLP / sensitivity labels", "Data loss prevention.", "QA includes compliance paths.", "https://learn.microsoft.com/purview/"),
    api("studio", "Copilot Studio agents", "Build custom agents.", "Test topics and actions.", "https://learn.microsoft.com/microsoft-copilot-studio/"),
    api("eval", "response quality rubrics", "Score helpfulness/safety.", "Enterprise acceptance tests.", "https://learn.microsoft.com/microsoft-365-copilot/"),
    api("admin", "admin center controls", "Enablement & auditing.", "Rollout checklists.", "https://learn.microsoft.com/microsoft-365-copilot/"),
    api("integration", "Teams / Outlook surfaces", "Surface-specific UX.", "Automate where allowed.", "https://learn.microsoft.com/microsoft-365-copilot/"),
  ],

  jira: [
    api("issue-create", "POST /issue", "Create issues via API.", "Defect filing automation.", "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/"),
    api("jql", "JQL search", "Query issues precisely.", "Traceability reports.", "https://support.atlassian.com/jira-software-cloud/docs/what-is-advanced-search-in-jira-cloud/"),
    api("transitions", "transitions API", "Move issues across workflow.", "Status is a contract.", "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-transitions-post"),
    api("fields", "custom fields", "Read/write custom fields.", "QA metadata lives here.", "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-fields/"),
    api("links", "issue links", "Relate bugs to stories.", "Trace matrices.", "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-links/"),
    api("attachments", "add attachment", "Evidence on bugs.", "Logs and screenshots.", "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-attachments/"),
    api("webhooks", "jira webhooks", "React to issue events.", "ChatOps for failures.", "https://developer.atlassian.com/cloud/jira/platform/webhooks/"),
    api("boards", "agile boards API", "Sprint/board queries.", "Release readiness views.", "https://developer.atlassian.com/cloud/jira/software/rest/api-group-board/"),
    api("automation", "Jira Automation rules", "No-code workflows.", "Test rule side effects.", "https://support.atlassian.com/cloud-automation/docs/jira-cloud-automation/"),
  ],

  stlc: [
    api("requirements", "Requirements analysis", "Clarify testable criteria.", "Ambiguity is defect debt.", "https://www.istqb.org/"),
    api("planning", "Test planning", "Scope, risks, schedule.", "Plan ≠ strategy.", "https://www.istqb.org/"),
    api("design", "Test design techniques", "EP / BVA / decision tables.", "Design before scripts.", "https://www.istqb.org/"),
    api("implementation", "Test implementation", "Automate and data prep.", "Trace cases to reqs.", "https://www.istqb.org/"),
    api("execution", "Test execution", "Runs, blockers, evidence.", "Daily status discipline.", "https://www.istqb.org/"),
    api("reporting", "Test reporting", "Exit criteria & risks.", "Ship/no-ship narrative.", "https://www.istqb.org/"),
    api("closure", "Test closure", "Lessons learned / archives.", "Feed the next release.", "https://www.istqb.org/"),
    api("strategy", "Test strategy vs plan", "Strategy = approach; plan = instance.", "Governance clarity.", "https://www.istqb.org/"),
    api("defect-mgmt", "Defect lifecycle", "Severity/priority/reopen.", "Consistent defect data.", "https://support.atlassian.com/jira-software-cloud/docs/what-is-an-issue/"),
    api("traceability", "Requirements ↔ cases ↔ defects", "Trace matrices.", "Regulated domains expect them.", "https://www.istqb.org/"),
  ],
};
